var searchData=
[
  ['dokumentacja_20dla_20pliku_20_3ctt_3edatabaseconfigdialog_2ecpp_3c_2ftt_3e_0',['Dokumentacja dla pliku &lt;tt&gt;DatabaseConfigDialog.cpp&lt;/tt&gt;',['../md_documentation__database_config_dialog_cpp.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3edatabaseconfigdialog_2eh_3c_2ftt_3e_1',['Dokumentacja dla pliku &lt;tt&gt;DatabaseConfigDialog.h&lt;/tt&gt;',['../md_documentation__database_config_dialog_h.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3efullscreenphotoviewer_2ecpp_3c_2ftt_3e_2',['Dokumentacja dla pliku &lt;tt&gt;fullscreenphotoviewer.cpp&lt;/tt&gt;',['../md_documentation_fullscreenphotoviewer_cpp.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3efullscreenphotoviewer_2eh_3c_2ftt_3e_3',['Dokumentacja dla pliku &lt;tt&gt;fullscreenphotoviewer.h&lt;/tt&gt;',['../md_documentation_fullscreenphotoviewer_h.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3eitemfilterproxymodel_2ecpp_3c_2ftt_3e_4',['Dokumentacja dla pliku &lt;tt&gt;ItemFilterProxyModel.cpp&lt;/tt&gt;',['../md_documentation__item_filter_proxy_model_cpp.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3eitemfilterproxymodel_2eh_3c_2ftt_3e_5',['Dokumentacja dla pliku &lt;tt&gt;ItemFilterProxyModel.h&lt;/tt&gt;',['../md_documentation__item_filter_proxy_model_h.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3eitemlist_2ecpp_3c_2ftt_3e_6',['Dokumentacja dla pliku &lt;tt&gt;itemList.cpp&lt;/tt&gt;',['../md_documentation_item_list_cpp.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3eitemlist_2eh_3c_2ftt_3e_7',['Dokumentacja dla pliku &lt;tt&gt;itemList.h&lt;/tt&gt;',['../md_documentation_item_list_h.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3emain_2ecpp_3c_2ftt_3e_8',['Dokumentacja dla pliku &lt;tt&gt;main.cpp&lt;/tt&gt;',['../md_documentation_main.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3emainwindow_2ecpp_3c_2ftt_3e_9',['Dokumentacja dla pliku &lt;tt&gt;mainwindow.cpp&lt;/tt&gt;',['../md_documentation_mainwindow_cpp.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3emainwindow_2eh_3c_2ftt_3e_10',['Dokumentacja dla pliku &lt;tt&gt;mainwindow.h&lt;/tt&gt;',['../md_documentation_mainwindow_h.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3emodels_2ecpp_3c_2ftt_3e_11',['Dokumentacja dla pliku &lt;tt&gt;models.cpp&lt;/tt&gt;',['../md_documentation_models_cpp.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3emodels_2eh_3c_2ftt_3e_12',['Dokumentacja dla pliku &lt;tt&gt;models.h&lt;/tt&gt;',['../md_documentation_models_h.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3ephotoitem_2ecpp_3c_2ftt_3e_13',['Dokumentacja dla pliku &lt;tt&gt;photoitem.cpp&lt;/tt&gt;',['../md_documentation_photoitem_cpp.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3ephotoitem_2eh_3c_2ftt_3e_14',['Dokumentacja dla pliku &lt;tt&gt;photoitem.h&lt;/tt&gt;',['../md_documentation_photoitem_h.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3estatus_2ecpp_3c_2ftt_3e_15',['Dokumentacja dla pliku &lt;tt&gt;status.cpp&lt;/tt&gt;',['../md_documentation_status_cpp.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3estatus_2eh_3c_2ftt_3e_16',['Dokumentacja dla pliku &lt;tt&gt;status.h&lt;/tt&gt;',['../md_documentation_status_h.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3estorage_2ecpp_3c_2ftt_3e_17',['Dokumentacja dla pliku &lt;tt&gt;storage.cpp&lt;/tt&gt;',['../md_documentation_storage_cpp.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3estorage_2eh_3c_2ftt_3e_18',['Dokumentacja dla pliku &lt;tt&gt;storage.h&lt;/tt&gt;',['../md_documentation_storage_h.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3etypes_2ecpp_3c_2ftt_3e_19',['Dokumentacja dla pliku &lt;tt&gt;types.cpp&lt;/tt&gt;',['../md_documentation_types_cpp.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3etypes_2eh_3c_2ftt_3e_20',['Dokumentacja dla pliku &lt;tt&gt;types.h&lt;/tt&gt;',['../md_documentation_types_h.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3eutils_2ecpp_3c_2ftt_3e_21',['Dokumentacja dla pliku &lt;tt&gt;utils.cpp&lt;/tt&gt;',['../md_documentation_utils_cpp.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3eutils_2eh_3c_2ftt_3e_22',['Dokumentacja dla pliku &lt;tt&gt;utils.h&lt;/tt&gt;',['../md_documentation_utils_h.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3evendors_2ecpp_3c_2ftt_3e_23',['Dokumentacja dla pliku &lt;tt&gt;vendors.cpp&lt;/tt&gt;',['../md_documentation_vendors_cpp.html',1,'']]],
  ['dokumentacja_20dla_20pliku_20_3ctt_3evendors_2eh_3c_2ftt_3e_24',['Dokumentacja dla pliku &lt;tt&gt;vendors.h&lt;/tt&gt;',['../md_documentation_vendors_h.html',1,'']]],
  ['dziennik_20zmian_25',['Dziennik zmian',['../md__c_h_a_n_g_e_l_o_g.html',1,'']]]
];
