var annotated_dup =
[
    [ "QT_WARNING_DISABLE_DEPRECATED", null, [
      [ "qt_meta_tag_ZN10MainWindowE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n10_main_window_e__t.html", null ],
      [ "qt_meta_tag_ZN20DatabaseConfigDialogE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n20_database_config_dialog_e__t.html", null ],
      [ "qt_meta_tag_ZN20ItemFilterProxyModelE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n20_item_filter_proxy_model_e__t.html", null ],
      [ "qt_meta_tag_ZN20ZoomableGraphicsViewE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n20_zoomable_graphics_view_e__t.html", null ],
      [ "qt_meta_tag_ZN5typesE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n5types_e__t.html", null ],
      [ "qt_meta_tag_ZN6modelsE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n6models_e__t.html", null ],
      [ "qt_meta_tag_ZN6statusE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n6status_e__t.html", null ],
      [ "qt_meta_tag_ZN7storageE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n7storage_e__t.html", null ],
      [ "qt_meta_tag_ZN7vendorsE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n7vendors_e__t.html", null ],
      [ "qt_meta_tag_ZN8itemListE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n8item_list_e__t.html", null ],
      [ "qt_meta_tag_ZN9PhotoItemE_t", "struct_q_t___w_a_r_n_i_n_g___d_i_s_a_b_l_e___d_e_p_r_e_c_a_t_e_d_1_1qt__meta__tag___z_n9_photo_item_e__t.html", null ]
    ] ],
    [ "Ui", null, [
      [ "DatabaseConfigDialog", "class_ui_1_1_database_config_dialog.html", null ],
      [ "itemList", "class_ui_1_1item_list.html", null ],
      [ "MainWindow", "class_ui_1_1_main_window.html", null ],
      [ "models", "class_ui_1_1models.html", null ],
      [ "status", "class_ui_1_1status.html", null ],
      [ "storage", "class_ui_1_1storage.html", null ],
      [ "types", "class_ui_1_1types.html", null ],
      [ "vendors", "class_ui_1_1vendors.html", null ]
    ] ],
    [ "DatabaseConfigDialog", "class_database_config_dialog.html", "class_database_config_dialog" ],
    [ "FullScreenPhotoViewer", "class_full_screen_photo_viewer.html", "class_full_screen_photo_viewer" ],
    [ "ItemFilterProxyModel", "class_item_filter_proxy_model.html", "class_item_filter_proxy_model" ],
    [ "itemList", "classitem_list.html", "classitem_list" ],
    [ "MainWindow", "class_main_window.html", "class_main_window" ],
    [ "models", "classmodels.html", "classmodels" ],
    [ "PhotoItem", "class_photo_item.html", "class_photo_item" ],
    [ "status", "classstatus.html", "classstatus" ],
    [ "storage", "classstorage.html", "classstorage" ],
    [ "types", "classtypes.html", "classtypes" ],
    [ "Ui_DatabaseConfigDialog", "class_ui___database_config_dialog.html", null ],
    [ "Ui_itemList", "class_ui__item_list.html", null ],
    [ "Ui_MainWindow", "class_ui___main_window.html", null ],
    [ "Ui_models", "class_ui__models.html", null ],
    [ "Ui_status", "class_ui__status.html", null ],
    [ "Ui_storage", "class_ui__storage.html", null ],
    [ "Ui_types", "class_ui__types.html", null ],
    [ "Ui_vendors", "class_ui__vendors.html", null ],
    [ "vendors", "classvendors.html", "classvendors" ],
    [ "ZoomableGraphicsView", "class_zoomable_graphics_view.html", "class_zoomable_graphics_view" ]
];