.TH "DatabaseConfigDialog" 3 "So, 3 maj 2025" "Version 1.1.2" "Inwentaryzacja" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DatabaseConfigDialog \- Okno dialogowe do konfiguracji połączenia z bazą danych i wyboru skórki graficznej\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DatabaseConfigDialog\&.h>\fP
.PP
Dziedziczy QDialog\&.
.SS "Sloty publiczne"

.in +1c
.ti -1c
.RI "void \fBaccept\fP () override"
.br
.RI "Zatwierdza wprowadzone dane i zamyka okno dialogowe\&. "
.in -1c
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "\fBDatabaseConfigDialog\fP (QWidget *parent=nullptr)"
.br
.RI "Konstruktor klasy \fBDatabaseConfigDialog\fP\&. "
.ti -1c
.RI "\fB~DatabaseConfigDialog\fP ()"
.br
.RI "Destruktor klasy \fBDatabaseConfigDialog\fP\&. "
.ti -1c
.RI "QString \fBselectedDatabaseType\fP () const"
.br
.RI "Zwraca wybrany typ bazy danych\&. "
.ti -1c
.RI "QString \fBsqliteFilePath\fP () const"
.br
.RI "Zwraca ścieżkę do pliku bazy SQLite\&. "
.ti -1c
.RI "QString \fBmysqlHost\fP () const"
.br
.RI "Zwraca adres hosta dla bazy MySQL\&. "
.ti -1c
.RI "QString \fBmysqlDatabase\fP () const"
.br
.RI "Zwraca nazwę bazy danych MySQL\&. "
.ti -1c
.RI "QString \fBmysqlUser\fP () const"
.br
.RI "Zwraca nazwę użytkownika dla bazy MySQL\&. "
.ti -1c
.RI "QString \fBmysqlPassword\fP () const"
.br
.RI "Zwraca hasło użytkownika dla bazy MySQL\&. "
.ti -1c
.RI "int \fBmysqlPort\fP () const"
.br
.RI "Zwraca numer portu dla bazy MySQL\&. "
.in -1c
.SH "Opis szczegółowy"
.PP 
Okno dialogowe do konfiguracji połączenia z bazą danych i wyboru skórki graficznej\&. 


.SH "ClassOverview"
.PP
Klasa \fBDatabaseConfigDialog\fP dziedziczy po QDialog i dostarcza interfejs graficzny do wprowadzania parametrów połączenia z bazą danych oraz wyboru skórki graficznej\&. Obsługuje dwa typy baz danych (SQLite i MySQL) oraz cztery skórki graficzne (Amiga, Atari 8bit, ZX Spectrum, Standard)\&. Po zatwierdzeniu ustawienia są zapisywane w QSettings, a metody dostępowe pozwalają na pobranie parametrów w innych częściach aplikacji\&.
.SH "Responsibilities"
.PP
.IP "\(bu" 2
Wyświetlanie i zarządzanie oknem dialogowym z polami do konfiguracji bazy danych\&.
.IP "\(bu" 2
Dynamiczne przełączanie interfejsu w zależności od typu bazy danych\&.
.IP "\(bu" 2
Ładowanie i stosowanie arkuszy stylów (QSS) oraz czcionek dla wybranych skórek\&.
.IP "\(bu" 2
Trwałe przechowywanie ustawień w pliku inwentaryzacja\&.ini\&. 
.PP

.SH "Dokumentacja konstruktora i destruktora"
.PP 
.SS "DatabaseConfigDialog::DatabaseConfigDialog (QWidget * parent = \fCnullptr\fP)\fC [explicit]\fP"

.PP
Konstruktor klasy \fBDatabaseConfigDialog\fP\&. 
.PP
\fBParametry\fP
.RS 4
\fIparent\fP Wskaźnik na nadrzędny widget\&. Domyślnie nullptr\&.
.RE
.PP
.SH "ConstructorOverview"
.PP
Inicjalizuje okno dialogowe, konfiguruje interfejs użytkownika (ui), ładuje dostępne skórki graficzne, ustawia opcje combo boxów i wczytuje zapisane ustawienia z QSettings\&. Ustawia połączenia sygnałów i slotów dla dynamicznej interakcji z użytkownikiem\&.
.PP
\fBParametry\fP
.RS 4
\fIparent\fP Wskaźnik na nadrzędny widget\&. Domyślnie nullptr\&.
.RE
.PP
.SH "ConstructorOverview"
.PP
Inicjalizuje interfejs użytkownika, ustawia opcje combo boxów dla typu bazy danych (SQLite3, MySQL) i skórek graficznych (Amiga, Atari 8bit, ZX Spectrum, Standard)\&. Ładuje zapisane ustawienia z QSettings, konfiguruje początkowy stan interfejsu i ustanawia połączenia sygnałów-slotów dla interakcji użytkownika, w tym wybór pliku SQLite\&. 
.SS "DatabaseConfigDialog::~DatabaseConfigDialog ()"

.PP
Destruktor klasy \fBDatabaseConfigDialog\fP\&. 
.SH "DestructorOverview"
.PP
Zwalnia zasoby interfejsu użytkownika (ui) oraz usuwa załadowane czcionki z QFontDatabase, aby zapobiec wyciekom pamięci\&.
.SH "DestructorOverview"
.PP
Zwalnia zasoby interfejsu użytkownika (ui) oraz usuwa załadowane czcionki (Topaz, ZX Spectrum, Atari 8bit) z QFontDatabase, aby zapobiec wyciekom pamięci\&. 
.SH "Dokumentacja funkcji składowych"
.PP 
.SS "void DatabaseConfigDialog::accept ()\fC [override]\fP, \fC [slot]\fP"

.PP
Zatwierdza wprowadzone dane i zamyka okno dialogowe\&. 
.SH "SlotOverview"
.PP
Przesłania metodę \fBaccept()\fP klasy QDialog\&. Zapisuje wszystkie wprowadzone parametry (typ bazy danych, ścieżka SQLite, dane MySQL, wybrana skórka) w QSettings i zamyka okno dialogowe z wynikiem QDialog::Accepted\&.
.SH "MethodOverview"
.PP
Zapisuje wszystkie wprowadzone parametry (typ bazy danych, ścieżka SQLite, dane MySQL, wybrana skórka) w pliku inwentaryzacja\&.ini za pomocą QSettings, a następnie wywołuje metodę accept klasy QDialog, zamykając okno z wynikiem QDialog::Accepted\&. 
.SS "QString DatabaseConfigDialog::mysqlDatabase () const"

.PP
Zwraca nazwę bazy danych MySQL\&. 
.PP
\fBZwraca\fP
.RS 4
QString zawierający nazwę bazy danych MySQL\&.
.RE
.PP
.SH "MethodOverview"
.PP
Zwraca nazwę bazy danych MySQL wprowadzoną w polu databaseLineEdit\&.
.PP
\fBZwraca\fP
.RS 4
QString zawierający nazwę bazy danych MySQL\&.
.RE
.PP
.SH "MethodOverview"
.PP
Zwraca tekst z pola databaseLineEdit, zawierający nazwę bazy danych MySQL\&. 
.SS "QString DatabaseConfigDialog::mysqlHost () const"

.PP
Zwraca adres hosta dla bazy MySQL\&. 
.PP
\fBZwraca\fP
.RS 4
QString zawierający adres hosta MySQL\&.
.RE
.PP
.SH "MethodOverview"
.PP
Zwraca adres hosta MySQL wprowadzony w polu hostLineEdit\&.
.PP
\fBZwraca\fP
.RS 4
QString zawierający adres hosta MySQL\&.
.RE
.PP
.SH "MethodOverview"
.PP
Zwraca tekst z pola hostLineEdit, zawierający adres hosta bazy MySQL\&. 
.SS "QString DatabaseConfigDialog::mysqlPassword () const"

.PP
Zwraca hasło użytkownika dla bazy MySQL\&. 
.PP
\fBZwraca\fP
.RS 4
QString zawierający hasło użytkownika MySQL\&.
.RE
.PP
.SH "MethodOverview"
.PP
Zwraca hasło użytkownika MySQL wprowadzone w polu passwordLineEdit\&.
.PP
\fBZwraca\fP
.RS 4
QString zawierający hasło użytkownika MySQL\&.
.RE
.PP
.SH "MethodOverview"
.PP
Zwraca tekst z pola passwordLineEdit, zawierający hasło użytkownika bazy MySQL\&. 
.SS "int DatabaseConfigDialog::mysqlPort () const"

.PP
Zwraca numer portu dla bazy MySQL\&. 
.PP
\fBZwraca\fP
.RS 4
int zawierający numer portu MySQL\&.
.RE
.PP
.SH "MethodOverview"
.PP
Zwraca numer portu MySQL wprowadzony w polu portSpinBox\&.
.PP
\fBZwraca\fP
.RS 4
int zawierający numer portu MySQL\&.
.RE
.PP
.SH "MethodOverview"
.PP
Zwraca wartość z pola portSpinBox, reprezentującą numer portu bazy MySQL\&. 
.SS "QString DatabaseConfigDialog::mysqlUser () const"

.PP
Zwraca nazwę użytkownika dla bazy MySQL\&. 
.PP
\fBZwraca\fP
.RS 4
QString zawierający nazwę użytkownika MySQL\&.
.RE
.PP
.SH "MethodOverview"
.PP
Zwraca nazwę użytkownika MySQL wprowadzoną w polu userLineEdit\&.
.PP
\fBZwraca\fP
.RS 4
QString zawierający nazwę użytkownika MySQL\&.
.RE
.PP
.SH "MethodOverview"
.PP
Zwraca tekst z pola userLineEdit, zawierający nazwę użytkownika bazy MySQL\&. 
.SS "QString DatabaseConfigDialog::selectedDatabaseType () const"

.PP
Zwraca wybrany typ bazy danych\&. 
.PP
\fBZwraca\fP
.RS 4
QString zawierający typ bazy danych (np\&. 'SQLite3' lub 'MySQL')\&.
.RE
.PP
.SH "MethodOverview"
.PP
Pobiera aktualnie wybrany typ bazy danych z combo boxa dbTypeComboBox\&.
.PP
\fBZwraca\fP
.RS 4
QString zawierający typ bazy danych\&.
.RE
.PP
.SH "MethodOverview"
.PP
Pobiera tekst wybrany w combo boxie dbTypeComboBox, reprezentujący typ bazy danych (SQLite3 lub MySQL)\&. 
.SS "QString DatabaseConfigDialog::sqliteFilePath () const"

.PP
Zwraca ścieżkę do pliku bazy SQLite\&. 
.PP
\fBZwraca\fP
.RS 4
QString zawierający ścieżkę do pliku SQLite\&.
.RE
.PP
.SH "MethodOverview"
.PP
Zwraca ścieżkę do pliku bazy SQLite wprowadzoną w polu sqlitePathLineEdit\&.
.PP
\fBZwraca\fP
.RS 4
QString zawierający ścieżkę do pliku SQLite\&.
.RE
.PP
.SH "MethodOverview"
.PP
Zwraca tekst z pola sqlitePathLineEdit, zawierający ścieżkę do pliku bazy SQLite\&. 

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Inwentaryzacja\&.
