.TH "include/fullscreenphotoviewer.h" 3 "So, 3 maj 2025" "Version 1.1.2" "Inwentaryzacja" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/fullscreenphotoviewer.h \- Deklaracja klas \fBZoomableGraphicsView\fP i \fBFullScreenPhotoViewer\fP do pełnoekranowego podglądu zdjęć\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <QGraphicsScene>\fP
.br
\fC#include <QGraphicsView>\fP
.br
\fC#include <QKeyEvent>\fP
.br
\fC#include <QMainWindow>\fP
.br
\fC#include <QWheelEvent>\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBZoomableGraphicsView\fP"
.br
.RI "Widok graficzny umożliwiający powiększanie i przesuwanie obrazu\&. "
.ti -1c
.RI "class \fBFullScreenPhotoViewer\fP"
.br
.RI "Okno pełnoekranowe do wyświetlania zdjęć\&. "
.in -1c
.SH "Opis szczegółowy"
.PP 
Deklaracja klas \fBZoomableGraphicsView\fP i \fBFullScreenPhotoViewer\fP do pełnoekranowego podglądu zdjęć\&. 


.PP
\fBAutor\fP
.RS 4
Stowarzyszenie Miłośników Oldschoolowych Komputerów SMOK & ChatGPT & GROK 
.RE
.PP
\fBWersja\fP
.RS 4
1\&.2\&.2 
.RE
.PP
\fBData\fP
.RS 4
2025-05-03
.RE
.PP
.SH "Overview"
.PP
Plik \fBfullscreenphotoviewer\&.h\fP definiuje dwie klasy: \fBZoomableGraphicsView\fP oraz \fBFullScreenPhotoViewer\fP, używane w aplikacji inwentaryzacyjnej do pełnoekranowego wyświetlania zdjęć eksponatów\&. Klasa \fBZoomableGraphicsView\fP umożliwia powiększanie i przesuwanie obrazu za pomocą kółka myszy i przeciągania, natomiast \fBFullScreenPhotoViewer\fP tworzy bezramkowe okno pełnoekranowe z możliwością zamknięcia klawiszem Escape\&.
.SH "Structure"
.PP
Plik nagłówkowy zawiera:
.IP "1." 4
\fBDeklarację klasy \fBZoomableGraphicsView\fP\fP – dziedziczy po QGraphicsView, implementuje powiększanie i przesuwanie\&.
.IP "2." 4
\fBDeklarację klasy \fBFullScreenPhotoViewer\fP\fP – dziedziczy po QMainWindow, zarządza pełnoekranowym wyświetlaniem zdjęcia\&.
.IP "3." 4
\fBMetody inline\fP – wszystkie metody są zdefiniowane w pliku nagłówkowym, eliminując potrzebę osobnego pliku \&.cpp\&.
.PP
.SH "Dependencies"
.PP
.IP "\(bu" 2
\fBQt Framework\fP: Używa klas QMainWindow, QGraphicsView, QGraphicsScene, QKeyEvent, QWheelEvent\&.
.IP "\(bu" 2
\fBZasoby\fP: Brak bezpośrednich zależności od zasobów Qt (np\&. plików QSS czy czcionek)\&.
.PP
.SH "Notes"
.PP
.IP "\(bu" 2
Kod nie został zmodyfikowany, zgodnie z wymaganiami użytkownika\&. Dodano jedynie komentarze i dokumentację\&.
.IP "\(bu" 2
Obie klasy są zoptymalizowane pod kątem prostoty i wydajności, z implementacją inline w pliku nagłówkowym\&.
.IP "\(bu" 2
\fBFullScreenPhotoViewer\fP jest modalny i automatycznie usuwa się po zamknięciu, co zapobiega wyciekom pamięci\&. 
.PP

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Inwentaryzacja\&.
