.TH "include/itemList.h" 3 "So, 3 maj 2025" "Version 1.1.2" "Inwentaryzacja" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/itemList.h \- Deklaracja klasy \fBitemList\fP, odpowiedzialnej za zarządzanie listą eksponatów w aplikacji inwentaryzacyjnej\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <QComboBox>\fP
.br
\fC#include <QItemSelection>\fP
.br
\fC#include <QLabel>\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include <QSqlRelationalTableModel>\fP
.br
\fC#include <QWidget>\fP
.br
\fC#include 'ItemFilterProxyModel\&.h'\fP
.br
\fC#include 'photoitem\&.h'\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBitemList\fP"
.br
.RI "Widget zarządzający listą eksponatów z interfejsem użytkownika\&. "
.in -1c
.SH "Opis szczegółowy"
.PP 
Deklaracja klasy \fBitemList\fP, odpowiedzialnej za zarządzanie listą eksponatów w aplikacji inwentaryzacyjnej\&. 


.PP
\fBAutor\fP
.RS 4
Stowarzyszenie Miłośników Oldschoolowych Komputerów SMOK & ChatGPT & GROK 
.RE
.PP
\fBWersja\fP
.RS 4
1\&.2\&.2 
.RE
.PP
\fBData\fP
.RS 4
2025-05-03
.RE
.PP
.SH "Overview"
.PP
Klasa \fBitemList\fP reprezentuje widget wyświetlający tabelę eksponatów z możliwością filtrowania, edycji, dodawania, usuwania i klonowania rekordów\&. Obsługuje interakcję z miniaturami zdjęć, podgląd pełnoekranowy oraz dynamiczne filtrowanie danych\&. Skórka graficzna i czcionki są zarządzane przez klasę \fBDatabaseConfigDialog\fP\&.
.SH "Structure"
.PP
Plik nagłówkowy zawiera:
.IP "1." 4
\fBDeklarację klasy \fBitemList\fP\fP – dziedziczy po QWidget\&.
.IP "2." 4
\fBMetody publiczne\fP – konstruktor i destruktor\&.
.IP "3." 4
\fBSloty prywatne\fP – obsługują interakcje użytkownika (przyciski, tabela, zdjęcia)\&.
.IP "4." 4
\fBMetody prywatne\fP – zarządzają schematem bazy danych, filtrami i zdarzeniami\&.
.IP "5." 4
\fBZmienne prywatne\fP – przechowują model danych, filtry, timery i stan interfejsu\&.
.PP
.SH "Dependencies"
.PP
.IP "\(bu" 2
\fBQt Framework\fP: Używa klas QWidget, QComboBox, QSqlRelationalTableModel, QSettings, QLabel, QItemSelection\&.
.IP "\(bu" 2
\fBNagłówki aplikacji\fP: \fBItemFilterProxyModel\&.h\fP, \fBphotoitem\&.h\fP\&.
.IP "\(bu" 2
\fBNamespace Ui\fP: Zawiera definicję interfejsu użytkownika (\fBui_itemList\&.h\fP)\&.
.PP
.SH "Notes"
.PP
.IP "\(bu" 2
Kod nie został zmodyfikowany, zgodnie z wymaganiami użytkownika\&. Dodano jedynie komentarze i dokumentację\&.
.IP "\(bu" 2
Klasa jest centralnym komponentem aplikacji, integrującym interfejs użytkownika z danymi bazy danych\&.
.IP "\(bu" 2
Obsługuje zarówno SQLite, jak i MySQL, z konfiguracją zarządzaną przez \fBDatabaseConfigDialog\fP\&. 
.PP

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Inwentaryzacja\&.
