.TH "src/ItemFilterProxyModel.cpp" 3 "So, 3 maj 2025" "Version 1.1.2" "Inwentaryzacja" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ItemFilterProxyModel.cpp \- Implementacja klasy \fBItemFilterProxyModel\fP do filtrowania listy eksponatów\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'ItemFilterProxyModel\&.h'\fP
.br
\fC#include <QModelIndex>\fP
.br

.SH "Opis szczegółowy"
.PP 
Implementacja klasy \fBItemFilterProxyModel\fP do filtrowania listy eksponatów\&. 


.PP
\fBAutor\fP
.RS 4
Stowarzyszenie Miłośników Oldschoolowych Komputerów SMOK & ChatGPT & GROK 
.RE
.PP
\fBWersja\fP
.RS 4
1\&.2\&.2 
.RE
.PP
\fBData\fP
.RS 4
2025-05-03
.RE
.PP
.SH "Overview"
.PP
Plik \fBItemFilterProxyModel\&.cpp\fP zawiera implementację metod klasy \fBItemFilterProxyModel\fP, która umożliwia dynamiczne filtrowanie listy eksponatów na podstawie atrybutów takich jak typ, producent, model, status i miejsce przechowywania\&. Klasa korzysta z mechanizmu QSortFilterProxyModel, umożliwiając filtrowanie wierszy modelu źródłowego (np\&. QSqlRelationalTableModel) z ignorowaniem wielkości liter\&.
.SH "Structure"
.PP
Kod jest podzielony na następujące sekcje:
.IP "1." 4
\fBKonstruktor\fP – inicjalizuje model proxy i konfiguruje filtrowanie\&.
.IP "2." 4
\fBMetody ustawiania filtrów\fP – zapisują wartości filtrów i odświeżają widok\&.
.IP "3." 4
\fBMetoda filterAcceptsRow\fP – implementuje logikę filtrowania wierszy\&.
.PP
.SH "Dependencies"
.PP
.IP "\(bu" 2
\fBQt Framework\fP: Używa klas QSortFilterProxyModel, QModelIndex, QAbstractItemModel\&.
.IP "\(bu" 2
\fBNagłówek\fP: \fBItemFilterProxyModel\&.h\fP\&.
.PP
.SH "Notes"
.PP
.IP "\(bu" 2
Kod nie został zmodyfikowany, zgodnie z wymaganiami użytkownika\&. Dodano jedynie komentarze i dokumentację\&.
.IP "\(bu" 2
Filtrowanie jest niezależne od wielkości liter, co ułatwia dopasowanie wartości\&.
.IP "\(bu" 2
Klasa zakłada, że model źródłowy ma określoną strukturę kolumn (np\&. typ w kolumnie 2)\&. 
.PP

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Inwentaryzacja\&.
