.TH "src/mainwindow.cpp" 3 "So, 3 maj 2025" "Version 1.1.2" "Inwentaryzacja" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mainwindow.cpp \- Implementacja klasy \fBMainWindow\fP do zarządzania formularzem eksponatów\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'ui_mainwindow\&.h'\fP
.br
\fC#include <QCompleter>\fP
.br
\fC#include <QDate>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <QDir>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QFileInfo>\fP
.br
\fC#include <QGraphicsPixmapItem>\fP
.br
\fC#include <QGraphicsScene>\fP
.br
\fC#include <QGuiApplication>\fP
.br
\fC#include <QInputDialog>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QScreen>\fP
.br
\fC#include <QSettings>\fP
.br
\fC#include <QSqlError>\fP
.br
\fC#include <QSqlQuery>\fP
.br
\fC#include <QUuid>\fP
.br
\fC#include 'models\&.h'\fP
.br
\fC#include 'photoitem\&.h'\fP
.br
\fC#include 'status\&.h'\fP
.br
\fC#include 'storage\&.h'\fP
.br
\fC#include 'types\&.h'\fP
.br
\fC#include 'vendors\&.h'\fP
.br

.SH "Opis szczegółowy"
.PP 
Implementacja klasy \fBMainWindow\fP do zarządzania formularzem eksponatów\&. 


.PP
\fBAutor\fP
.RS 4
Stowarzyszenie Miłośników Oldschoolowych Komputerów SMOK & ChatGPT & GROK 
.RE
.PP
\fBWersja\fP
.RS 4
1\&.2\&.2 
.RE
.PP
\fBData\fP
.RS 4
2025-05-03
.RE
.PP
.SH "Overview"
.PP
Plik zawiera implementację metod klasy \fBMainWindow\fP, odpowiedzialnej za formularz do dodawania, edycji i klonowania eksponatów w aplikacji inwentaryzacyjnej\&. Klasa obsługuje ładowanie danych do combo boxów, zarządzanie zdjęciami (w bazie i buforze), zapisywanie rekordów w bazie danych MySQL oraz otwieranie dialogów słownikowych\&. Implementacja obejmuje również automatyczne dodawanie nowych wartości do słowników po ich wpisaniu w combo boxach\&.
.SH "Structure"
.PP
Kod jest podzielony na następujące sekcje:
.IP "1." 4
\fBKonstruktor\fP – inicjalizuje interfejs, połączenie z bazą danych, combo boxy i sloty\&.
.IP "2." 4
\fBDestruktor\fP – zwalnia zasoby\&.
.IP "3." 4
\fBMetody publiczne\fP – ładowanie danych do combo boxów, ustawianie trybów, dostęp do combo boxów\&.
.IP "4." 4
\fBSloty prywatne\fP – obsługują akcje użytkownika (zapis, anulowanie, zdjęcia, słowniki)\&.
.IP "5." 4
\fBMetody prywatne\fP – wczytywanie rekordów i zdjęć\&.
.PP
.SH "Dependencies"
.PP
.IP "\(bu" 2
\fBQt Framework\fP: Używa klas QSqlQuery, QFileDialog, QMessageBox, QGraphicsScene, QCompleter, itp\&.
.IP "\(bu" 2
\fBNagłówki aplikacji\fP: \fBmainwindow\&.h\fP, \fBphotoitem\&.h\fP, \fBtypes\&.h\fP, \fBmodels\&.h\fP, \fBvendors\&.h\fP, \fBstatus\&.h\fP, \fBstorage\&.h\fP\&.
.IP "\(bu" 2
\fBInterfejs użytkownika\fP: \fBui_mainwindow\&.h\fP\&.
.PP
.SH "Notes"
.PP
.IP "\(bu" 2
Kod nie został zmodyfikowany, zgodnie z wymaganiami użytkownika\&. Dodano jedynie komentarze i dokumentację\&.
.IP "\(bu" 2
Klasa obsługuje tylko MySQL w tej implementacji, choć aplikacja wspiera także SQLite (konfigurowane w \fBDatabaseConfigDialog\fP)\&.
.IP "\(bu" 2
Automatyczne dodawanie wartości do słowników wymaga wybrania producenta dla modeli\&. 
.PP

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Inwentaryzacja\&.
