.TH "md_documentation_utils_h" 3 "So, 3 maj 2025" "Version 1.1.2" "Inwentaryzacja" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_documentation_utils_h \- Dokumentacja dla pliku \fC\fButils\&.h\fP\fP 

.SH "Metadane"
.PP
.IP "\(bu" 2
\fBPlik\fP: \fButils\&.h\fP
.IP "\(bu" 2
\fBWersja\fP: 1\&.2\&.2
.IP "\(bu" 2
\fBData\fP: 2025-05-03
.IP "\(bu" 2
\fBAutorzy\fP: Stowarzyszenie Miłośników Oldschoolowych Komputerów SMOK & ChatGPT & GROK
.PP
.SH "Przegląd"
.PP
Plik \fC\fButils\&.h\fP\fP definiuje funkcję \fCsetupDatabase\fP, która jest odpowiedzialna za inicjalizację połączenia z bazą danych w aplikacji inwentaryzacyjnej\&. Funkcja umożliwia konfigurację połączenia dla baz SQLite (lokalny plik) lub MySQL (zdalne połączenie), rejestrując je pod nazwą 'default_connection'\&. Jest to kluczowy komponent aplikacji, wykorzystywany na etapie uruchamiania, np\&. przez \fC\fBDatabaseConfigDialog\fP\fP, do przygotowania bazy danych dla innych komponentów, takich jak \fC\fBMainWindow\fP\fP, \fCtypes\fP, \fCstatus\fP, \fCstorage\fP czy \fCmodels\fP\&.
.SH "Struktura kodu"
.PP
Plik nagłówkowy zawiera następujące elementy:
.PP
.IP "1." 4
\fBDeklaracja funkcji \fCsetupDatabase\fP\fP 
.br
.IP "  \(bu" 4
Przyjmuje parametry określające typ bazy, źródło danych, host, użytkownika, hasło i port\&.
.IP "  \(bu" 4
Zwraca \fCbool\fP wskazujący sukces lub niepowodzenie połączenia\&.
.PP

.IP "2." 4
\fBZależności\fP 
.br
.IP "  \(bu" 4
Minimalne, tylko \fCQString\fP z Qt dla parametrów wejściowych\&.
.PP

.PP
.SH "Opis działania"
.PP
.IP "\(bu" 2
\fBCel funkcji\fP: Utworzenie i zarejestrowanie globalnego połączenia \fCQSqlDatabase\fP pod nazwą 'default_connection', które jest współdzielone przez wszystkie komponenty aplikacji\&.
.IP "\(bu" 2
\fBObsługiwane bazy danych\fP:
.IP "  \(bu" 4
\fBSQLite\fP (\fCQSQLITE\fP): Używa ścieżki do pliku jako \fCdbSource\fP\&. Automatycznie tworzy schemat bazy i przykładowe dane (implementacja w \fC\fButils\&.cpp\fP\fP)\&.
.IP "  \(bu" 4
\fBMySQL\fP (\fCQMYSQL\fP): Używa nazwy bazy danych jako \fCdbSource\fP, wymaga parametrów \fChost\fP, \fCuser\fP, \fCpassword\fP, \fCport\fP\&.
.PP

.IP "\(bu" 2
\fBParametry\fP:
.IP "  \(bu" 4
\fCdbType\fP: Określa typ bazy ('SQLite3' lub 'MySQL')\&.
.IP "  \(bu" 4
\fCdbSource\fP: Ścieżka do pliku (SQLite) lub nazwa bazy (MySQL)\&.
.IP "  \(bu" 4
\fChost\fP, \fCuser\fP, \fCpassword\fP, \fCport\fP: Opcjonalne dla MySQL, ignorowane dla SQLite\&.
.PP

.IP "\(bu" 2
\fBZwracana wartość\fP: \fCtrue\fP po pomyślnym nawiązaniu połączenia, \fCfalse\fP w przypadku błędu (np\&. nieprawidłowe dane uwierzytelniające, brak pliku bazy)\&.
.PP
.SH "Zależności"
.PP
.IP "\(bu" 2
\fBBiblioteki Qt\fP:
.IP "  \(bu" 4
\fCQString\fP: Do obsługi parametrów wejściowych\&.
.IP "  \(bu" 4
Pośrednio: \fCQSqlDatabase\fP (używane w \fC\fButils\&.cpp\fP\fP)\&.
.PP

.IP "\(bu" 2
\fBNagłówki aplikacji\fP:
.IP "  \(bu" 4
Brak zależności od innych nagłówków aplikacji\&.
.PP

.IP "\(bu" 2
\fBZasoby\fP:
.IP "  \(bu" 4
Brak bezpośrednich zależności od zasobów Qt (np\&. QSS, czcionek)\&.
.PP

.PP
.SH "Uwagi"
.PP
.IP "\(bu" 2
Kod nie został zmodyfikowany, zgodnie z wymaganiami użytkownika\&.
.IP "\(bu" 2
Funkcja \fCsetupDatabase\fP jest centralnym punktem konfiguracji bazy danych, używanym przez inne komponenty aplikacji\&.
.IP "\(bu" 2
Połączenie 'default_connection' jest współdzielone, co wymaga ostrożnego zarządzania w przypadku wielokrotnego wywoływania funkcji\&.
.IP "\(bu" 2
Obsługuje zarówno SQLite, jak i MySQL, co zwiększa elastyczność aplikacji\&.
.IP "\(bu" 2
Dokumentacja implementacji (w \fC\fButils\&.cpp\fP\fP) zawiera szczegóły dotyczące automatycznego tworzenia schematu dla SQLite\&. 
.PP

