.TH "md_documentation_photoitem_cpp" 3 "So, 3 maj 2025" "Version 1.1.2" "Inwentaryzacja" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_documentation_photoitem_cpp \- Dokumentacja dla pliku \fC\fBphotoitem\&.cpp\fP\fP 

.SH "Metadane"
.PP
.IP "\(bu" 2
\fBPlik\fP: \fBphotoitem\&.cpp\fP
.IP "\(bu" 2
\fBWersja\fP: 1\&.2\&.2
.IP "\(bu" 2
\fBData\fP: 2025-05-03
.IP "\(bu" 2
\fBAutorzy\fP: Stowarzyszenie Miłośników Oldschoolowych Komputerów SMOK & ChatGPT & GROK
.PP
.SH "Przegląd"
.PP
Plik \fC\fBphotoitem\&.cpp\fP\fP zawiera implementację metod klasy \fC\fBPhotoItem\fP\fP, która reprezentuje interaktywną miniaturę zdjęcia w scenie graficznej Qt (\fCQGraphicsView\fP) w aplikacji inwentaryzacyjnej\&. Klasa rozszerza \fCQGraphicsPixmapItem\fP o obsługę zdarzeń myszy (kliknięcia, podwójne kliknięcia) i hover (najechanie, opuszczenie), a także wizualne zaznaczanie za pomocą czerwonej ramki\&. Dzięki dziedziczeniu po \fCQObject\fP, umożliwia emisję sygnałów (\fCclicked\fP, \fCdoubleClicked\fP, \fChovered\fP, \fCunhovered\fP) do integracji z logiką aplikacji, np\&. z klasą \fC\fBMainWindow\fP\fP dla wyboru lub podglądu zdjęć eksponatów\&.
.SH "Struktura kodu"
.PP
Kod jest podzielony na następujące sekcje:
.PP
.IP "1." 4
\fBSekcja konstruktora\fP 
.br
.IP "  \(bu" 4
Inicjalizuje obiekt, ramkę graficzną i włącza zdarzenia hover\&.
.PP

.IP "2." 4
\fBSekcja destruktora\fP 
.br
.IP "  \(bu" 4
Zwalnia zasoby ramki\&.
.PP

.IP "3." 4
\fBSekcja metod publicznych\fP 
.br
.IP "  \(bu" 4
\fCsetSelected\fP: Ustawia stan zaznaczenia i aktualizuje ramkę\&.
.PP

.IP "4." 4
\fBSekcja metod chronionych\fP 
.br
.IP "  \(bu" 4
\fCmousePressEvent\fP: Obsługuje kliknięcia myszą\&.
.IP "  \(bu" 4
\fCmouseDoubleClickEvent\fP: Obsługuje podwójne kliknięcia\&.
.IP "  \(bu" 4
\fChoverEnterEvent\fP: Obsługuje najechanie kursorem\&.
.IP "  \(bu" 4
\fChoverLeaveEvent\fP: Obsługuje opuszczenie kursora\&.
.PP

.IP "5." 4
\fBSekcja metod prywatnych\fP 
.br
.IP "  \(bu" 4
\fCupdateFrame\fP: Aktualizuje wygląd ramki zaznaczenia\&.
.PP

.PP
.SH "Opis działania"
.PP
.IP "1." 4
\fBInicjalizacja\fP:
.IP "  \(bu" 4
Konstruktor tworzy obiekt jako \fCQObject\fP i \fCQGraphicsPixmapItem\fP, ustawia flagi \fCm_pressed\fP i \fCm_selected\fP na \fCfalse\fP, tworzy ramkę (\fCm_frame\fP) jako dziecko, włącza zdarzenia hover (\fCsetAcceptHoverEvents(true)\fP), wyłącza zdarzenia dotykowe i ustawia ramkę jako niewidoczną (\fCQt::NoPen\fP, \fCQt::NoBrush\fP)\&.
.IP "  \(bu" 4
Ramka ma wyższy priorytet rysowania (\fCsetZValue(1)\fP), aby była widoczna nad miniaturą\&.
.PP

.IP "2." 4
\fBInterfejs graficzny\fP:
.IP "  \(bu" 4
Wyświetla miniaturę zdjęcia (np\&. 80x80 pikseli w \fC\fBMainWindow\fP\fP) w \fCQGraphicsView\fP\&.
.IP "  \(bu" 4
Przy zaznaczeniu (\fCm_selected == true\fP), pokazuje czerwoną ramkę o szerokości 2 piksele, obejmującą miniaturę z marginesem (-2, +2 piksele)\&.
.PP

.IP "3." 4
\fBInterakcje\fP:
.IP "  \(bu" 4
\fBKliknięcia\fP (\fCmousePressEvent\fP):
.IP "    \(bu" 6
Prawe kliknięcie emituje \fCclicked\fP (np\&. dla podglądu zdjęcia w \fC\fBMainWindow\fP\fP)\&.
.IP "    \(bu" 6
Lewe kliknięcie jest przekazywane do \fCQGraphicsPixmapItem\fP, aby umożliwić wykrycie podwójnego kliknięcia\&.
.IP "    \(bu" 6
Inne przyciski są obsługiwane domyślnie\&.
.PP

.IP "  \(bu" 4
\fBPodwójne kliknięcia\fP (\fCmouseDoubleClickEvent\fP):
.IP "    \(bu" 6
Lewe podwójne kliknięcie emituje \fCdoubleClicked\fP (np\&. dla pełnoekranowego podglądu)\&.
.IP "    \(bu" 6
Inne przyciski są obsługiwane domyślnie\&.
.PP

.IP "  \(bu" 4
\fBHover\fP:
.IP "    \(bu" 6
Najechanie (\fChoverEnterEvent\fP) emituje \fChovered\fP (np\&. dla podświetlenia, nieużywane w \fC\fBMainWindow\fP\fP)\&.
.IP "    \(bu" 6
Opuszczenie (\fChoverLeaveEvent\fP) emituje \fCunhovered\fP (np\&. dla usunięcia podświetlenia)\&.
.PP

.IP "  \(bu" 4
Wszystkie zdarzenia są przekazywane do \fCQGraphicsPixmapItem\fP dla domyślnej obsługi\&.
.PP

.IP "4." 4
\fBZaznaczenie\fP:
.IP "  \(bu" 4
\fCsetSelected\fP ustawia \fCm_selected\fP i wywołuje \fCupdateFrame\fP\&.
.IP "  \(bu" 4
\fCupdateFrame\fP rysuje czerwoną ramkę (2 piksele) dla \fCm_selected == true\fP lub ukrywa ją (\fCQt::NoPen\fP) dla \fCm_selected == false\fP\&.
.IP "  \(bu" 4
Ramka jest dopasowana do granic miniatury (\fCboundingRect\fP) z marginesem\&.
.PP

.IP "5." 4
\fBIntegracja\fP:
.IP "  \(bu" 4
Sygnał \fCclicked\fP jest podłączony w \fC\fBMainWindow\fP\fP do \fConPhotoClicked\fP dla wyboru miniatury (np\&. do usunięcia lub podglądu)\&.
.IP "  \(bu" 4
Sygnał \fCdoubleClicked\fP może być użyty do pełnoekranowego podglądu (niezrealizowane w \fC\fBMainWindow\fP\fP)\&.
.IP "  \(bu" 4
Sygnały \fChovered\fP i \fCunhovered\fP są zdefiniowane, ale nieużywane w obecnej implementacji\&.
.PP

.PP
.SH "Zależności"
.PP
.IP "\(bu" 2
\fBBiblioteki Qt\fP:
.IP "  \(bu" 4
\fCQGraphicsSceneMouseEvent\fP, \fCQPainter\fP, \fCQPen\fP, \fCQUuid\fP: Obsługa zdarzeń myszy, rysowania i generowania UUID\&.
.PP

.IP "\(bu" 2
\fBNagłówki aplikacji\fP:
.IP "  \(bu" 4
\fC\fBphotoitem\&.h\fP\fP: Definicja klasy\&.
.PP

.IP "\(bu" 2
\fBZasoby\fP:
.IP "  \(bu" 4
Brak bezpośrednich zależności od zasobów Qt (np\&. QSS, czcionek)\&.
.PP

.PP
.SH "Uwagi"
.PP
.IP "\(bu" 2
Kod nie został zmodyfikowany, zgodnie z wymaganiami użytkownika\&.
.IP "\(bu" 2
Klasa jest zoptymalizowana dla miniatur zdjęć w \fC\fBMainWindow\fP\fP, ale sygnały \fChovered\fP i \fCunhovered\fP nie są wykorzystywane, co sugeruje możliwość dodania podświetlania lub tooltipów\&.
.IP "\(bu" 2
Flaga \fCm_pressed\fP jest zdefiniowana, ale nieużywana, co może wskazywać na planowane funkcje (np\&. przeciąganie miniatur)\&.
.IP "\(bu" 2
Ramka zaznaczenia jest statyczna (czerwona, 2 piksele), ale może być dostosowana (np\&. kolor, grubość) w przyszłych wersjach\&.
.IP "\(bu" 2
Obsługa prawego przycisku dla \fCclicked\fP może być rozszerzona o menu kontekstowe (np\&. 'Usuń', 'Podgląd')\&.
.IP "\(bu" 2
Klasa nie zależy od bazy danych ani innych komponentów aplikacji, co czyni ją uniwersalną dla scen graficznych Qt\&. 
.PP

