.TH "md_documentation__database_config_dialog_h" 3 "So, 3 maj 2025" "Version 1.1.2" "Inwentaryzacja" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_documentation__database_config_dialog_h \- Dokumentacja dla pliku \fC\fBDatabaseConfigDialog\&.h\fP\fP 

.SH "Metadane"
.PP
.IP "\(bu" 2
\fBPlik\fP: \fBDatabaseConfigDialog\&.h\fP
.IP "\(bu" 2
\fBWersja\fP: 1\&.2\&.2
.IP "\(bu" 2
\fBData\fP: 2025-05-03
.IP "\(bu" 2
\fBAutorzy\fP: Stowarzyszenie Miłośników Oldschoolowych Komputerów SMOK & ChatGPT & GROK
.PP
.SH "Przegląd"
.PP
Plik \fC\fBDatabaseConfigDialog\&.h\fP\fP definiuje klasę \fC\fBDatabaseConfigDialog\fP\fP, która reprezentuje okno dialogowe do konfiguracji parametrów połączenia z bazą danych (SQLite lub MySQL) oraz wyboru skórki graficznej aplikacji (Amiga, Atari 8bit, ZX Spectrum, Standard)\&. Klasa dostarcza metody dostępowe do parametrów bazy danych, obsługuje dynamiczną zmianę stylów i czcionek oraz zapisuje ustawienia w \fCQSettings\fP dla trwałości między sesjami aplikacji\&.
.SH "Struktura kodu"
.PP
Plik nagłówkowy zawiera następujące elementy:
.PP
.IP "1." 4
\fBDeklaracja klasy \fC\fBDatabaseConfigDialog\fP\fP\fP 
.br
.IP "  \(bu" 4
Klasa dziedziczy po \fCQDialog\fP i używa mechanizmu sygnałów i slotów Qt (\fCQ_OBJECT\fP)\&.
.IP "  \(bu" 4
Zawiera publiczne i prywatne metody oraz zmienne\&.
.PP

.IP "2." 4
\fBMetody publiczne\fP 
.br
.IP "  \(bu" 4
Konstruktor: Inicjalizuje okno dialogowe i interfejs użytkownika\&.
.IP "  \(bu" 4
Destruktor: Zwalnia zasoby i odrejestrowuje czcionki\&.
.IP "  \(bu" 4
Metody dostępowe: Zwracają parametry bazy danych (typ, ścieżka SQLite, dane MySQL)\&.
.PP

.IP "3." 4
\fBSloty publiczne\fP 
.br
.IP "  \(bu" 4
\fCaccept()\fP: Przesłania metodę \fCQDialog::accept\fP do zapisu ustawień w \fCQSettings\fP\&.
.PP

.IP "4." 4
\fBSloty prywatne\fP 
.br
.IP "  \(bu" 4
\fConDatabaseTypeChanged(int index)\fP: Obsługuje zmianę typu bazy danych w combo boxie\&.
.IP "  \(bu" 4
\fConSkinChanged(const QString &skin)\fP: Obsługuje zmianę skórki graficznej\&.
.PP

.IP "5." 4
\fBMetody prywatne\fP 
.br
.IP "  \(bu" 4
\fCloadStyleSheet(const QString &skin)\fP: Ładuje arkusz stylów QSS dla wybranej skórki\&.
.IP "  \(bu" 4
\fCloadFont(const QString &skin)\fP: Ładuje czcionkę dla wybranej skórki\&.
.PP

.IP "6." 4
\fBZmienne prywatne\fP 
.br
.IP "  \(bu" 4
\fCui\fP: Wskaźnik na obiekt interfejsu użytkownika\&.
.IP "  \(bu" 4
\fCm_topazFontId\fP, \fCm_zxFontId\fP, \fCm_atari8bitFontId\fP: Identyfikatory załadowanych czcionek\&.
.PP

.PP
.SH "Opis działania"
.PP
Klasa \fC\fBDatabaseConfigDialog\fP\fP odpowiada za:
.IP "\(bu" 2
\fBWyświetlanie okna dialogowego\fP: Użytkownik wybiera typ bazy danych (SQLite/MySQL) i wprowadza parametry połączenia za pomocą interfejsu graficznego\&.
.IP "\(bu" 2
\fBDynamiczne przełączanie interfejsu\fP: Używa \fCQStackedWidget\fP do pokazywania odpowiednich pól w zależności od typu bazy danych\&.
.IP "\(bu" 2
\fBWybór skórki graficznej\fP: Umożliwia wybór jednej z czterech skórek (Amiga, Atari 8bit, ZX Spectrum, Standard), co wpływa na styl (QSS) i czcionkę aplikacji\&.
.IP "\(bu" 2
\fBTrwałe przechowywanie ustawień\fP: Parametry bazy danych i wybrana skórka są zapisywane w pliku \fCinwentaryzacja\&.ini\fP za pomocą \fCQSettings\fP\&.
.IP "\(bu" 2
\fBMetody dostępowe\fP: Umożliwiają innym częściom aplikacji (np\&. \fC\fBmain\&.cpp\fP\fP) pobranie skonfigurowanych parametrów\&.
.PP
.SH "Zależności"
.PP
.IP "\(bu" 2
\fBBiblioteki Qt\fP:
.IP "  \(bu" 4
\fCQDialog\fP: Bazowa klasa dla okna dialogowego\&.
.IP "  \(bu" 4
\fCQString\fP: Obsługa ciągów znaków dla parametrów\&.
.PP

.IP "\(bu" 2
\fBNamespace \fCUi\fP\fP:
.IP "  \(bu" 4
Zawiera definicję interfejsu użytkownika (\fC\fBui_DatabaseConfigDialog\&.h\fP\fP) generowaną przez Qt Designer\&.
.PP

.IP "\(bu" 2
\fBZasoby\fP:
.IP "  \(bu" 4
Pliki QSS dla stylów (\fC:/styles/amiga\&.qss\fP, \fC:/styles/atari8bit\&.qss\fP, \fC:/styles/zxspectrum\&.qss\fP, \fC:/styles/default\&.qss\fP)\&.
.IP "  \(bu" 4
Czcionki (\fC:/fonts/topaz\&.ttf\fP, \fC:/fonts/zxspectrum\&.ttf\fP, \fC:/fonts/EightBit Atari-Ataripl\&.ttf\fP)\&.
.PP

.PP
.SH "Uwagi"
.PP
.IP "\(bu" 2
Kod nie został zmodyfikowany, zgodnie z wymaganiami użytkownika\&.
.IP "\(bu" 2
Klasa dynamicznie dostosowuje interfejs użytkownika do wybranego typu bazy danych\&.
.IP "\(bu" 2
Czcionki są ładowane z zasobów Qt i odrejestrowywane w destruktorze, aby zapobiec wyciekom pamięci\&.
.IP "\(bu" 2
W przypadku błędów ładowania zasobów (np\&. czcionek lub QSS) aplikacja przechodzi na domyślne ustawienia (czcionka systemowa, brak stylu)\&. 
.PP

