.TH "md_documentation__database_config_dialog_cpp" 3 "So, 3 maj 2025" "Version 1.1.2" "Inwentaryzacja" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_documentation__database_config_dialog_cpp \- Dokumentacja dla pliku \fC\fBDatabaseConfigDialog\&.cpp\fP\fP 

.SH "Metadane"
.PP
.IP "\(bu" 2
\fBPlik\fP: \fBDatabaseConfigDialog\&.cpp\fP
.IP "\(bu" 2
\fBWersja\fP: 1\&.2\&.2
.IP "\(bu" 2
\fBData\fP: 2025-05-03
.IP "\(bu" 2
\fBAutorzy\fP: Stowarzyszenie Miłośników Oldschoolowych Komputerów SMOK & ChatGPT & GROK
.PP
.SH "Przegląd"
.PP
Plik \fC\fBDatabaseConfigDialog\&.cpp\fP\fP zawiera implementację metod klasy \fC\fBDatabaseConfigDialog\fP\fP, odpowiedzialnej za konfigurację parametrów połączenia z bazą danych (SQLite lub MySQL) oraz wybór skórki graficznej aplikacji (Amiga, Atari 8bit, ZX Spectrum, Standard)\&. Implementacja obejmuje ładowanie stylów QSS, czcionek, zapis ustawień w \fCQSettings\fP oraz obsługę dynamicznego wyboru pliku SQLite z możliwością tworzenia nowego pliku \fC\&.db\fP\&.
.SH "Struktura kodu"
.PP
Kod jest podzielony na następujące sekcje:
.PP
.IP "1." 4
\fBSekcja pomocnicza\fP 
.br
.IP "  \(bu" 4
Funkcja \fCgetSettings()\fP: Tworzy i zwraca obiekt \fCQSettings\fP dla pliku \fCinwentaryzacja\&.ini\fP\&.
.PP

.IP "2." 4
\fBSekcja konstruktora\fP 
.br
.IP "  \(bu" 4
Inicjalizuje interfejs użytkownika, combo boxy, wczytuje zapisane ustawienia i ustanawia połączenia sygnałów-slotów\&.
.PP

.IP "3." 4
\fBSekcja destruktora\fP 
.br
.IP "  \(bu" 4
Zwalnia zasoby interfejsu i odrejestrowuje czcionki\&.
.PP

.IP "4." 4
\fBSekcja metod publicznych\fP 
.br
.IP "  \(bu" 4
Metody dostępowe do parametrów bazy danych\&.
.IP "  \(bu" 4
Metoda \fCaccept()\fP: Zapisuje ustawienia i zamyka okno dialogowe\&.
.PP

.IP "5." 4
\fBSekcja slotów prywatnych\fP 
.br
.IP "  \(bu" 4
\fConDatabaseTypeChanged(int index)\fP: Przełącza interfejs w zależności od typu bazy danych\&.
.IP "  \(bu" 4
\fConSkinChanged(const QString &skin)\fP: Aktualizuje styl i czcionkę dla wybranej skórki\&.
.PP

.IP "6." 4
\fBSekcja metod prywatnych\fP 
.br
.IP "  \(bu" 4
\fCloadStyleSheet(const QString &skin)\fP: Ładuje plik QSS dla wybranej skórki\&.
.IP "  \(bu" 4
\fCloadFont(const QString &skin)\fP: Ładuje czcionkę dla wybranej skórki\&.
.PP

.PP
.SH "Opis działania"
.PP
.IP "1." 4
\fBInicjalizacja\fP:
.IP "  \(bu" 4
Konstruktor konfiguruje interfejs użytkownika (\fCui->setupUi\fP), wypełnia combo boxy opcjami bazy danych (SQLite3, MySQL) i skórek graficznych (Amiga, Atari 8bit, ZX Spectrum, Standard)\&.
.IP "  \(bu" 4
Wczytuje zapisane ustawienia z \fCQSettings\fP i ustawia początkowe wartości pól (np\&. ścieżka SQLite, dane MySQL, wybrana skórka)\&.
.IP "  \(bu" 4
Ustanawia połączenia sygnałów-slotów dla przycisków, combo boxów i wyboru pliku SQLite\&.
.PP

.IP "2." 4
\fBWybór pliku SQLite\fP:
.IP "  \(bu" 4
Przycisk \fCselectFileButton\fP otwiera okno dialogowe \fCQFileDialog::getSaveFileName\fP, umożliwiając wybór istniejącego lub nowego pliku \fC\&.db\fP\&.
.IP "  \(bu" 4
Jeśli wybrany plik nie istnieje, tworzony jest pusty plik\&.
.PP

.IP "3." 4
\fBZmiana typu bazy danych\fP:
.IP "  \(bu" 4
Slot \fConDatabaseTypeChanged\fP przełącza strony w \fCQStackedWidget\fP, pokazując pola odpowiednie dla SQLite lub MySQL\&.
.PP

.IP "4." 4
\fBZmiana skórki graficznej\fP:
.IP "  \(bu" 4
Slot \fConSkinChanged\fP wywołuje \fCloadStyleSheet\fP i \fCloadFont\fP, aktualizując styl i czcionkę aplikacji\&.
.IP "  \(bu" 4
Wybór skórki jest zapisywany w \fCQSettings\fP\&.
.PP

.IP "5." 4
\fBZatwierdzanie ustawień\fP:
.IP "  \(bu" 4
Metoda \fCaccept\fP zapisuje wszystkie parametry (baza danych, skórka) w \fCQSettings\fP i zamyka okno dialogowe\&.
.PP

.IP "6." 4
\fBŁadowanie stylów i czcionek\fP:
.IP "  \(bu" 4
\fCloadStyleSheet\fP wczytuje plik QSS z zasobów Qt i stosuje go za pomocą \fCqApp->setStyleSheet\fP\&.
.IP "  \(bu" 4
\fCloadFont\fP ładuje czcionkę (np\&. \fCtopaz\&.ttf\fP dla Amigi) za pomocą \fCQFontDatabase\fP, ustawia ją dla aplikacji i resetuje paletę/styl dla propagacji zmian\&.
.PP

.PP
.SH "Zależności"
.PP
.IP "\(bu" 2
\fBBiblioteki Qt\fP:
.IP "  \(bu" 4
\fCQApplication\fP: Ustawianie stylów i czcionek dla aplikacji\&.
.IP "  \(bu" 4
\fCQDebug\fP, \fCqWarning\fP: Logowanie komunikatów diagnostycznych\&.
.IP "  \(bu" 4
\fCQDir\fP, \fCQFile\fP: Obsługa plików konfiguracyjnych i zasobów\&.
.IP "  \(bu" 4
\fCQFileDialog\fP: Wybór pliku SQLite\&.
.IP "  \(bu" 4
\fCQFontDatabase\fP: Ładowanie i zarządzanie czcionkami\&.
.IP "  \(bu" 4
\fCQPushButton\fP, \fCQSettings\fP: Obsługa interfejsu i zapisu ustawień\&.
.PP

.IP "\(bu" 2
\fBInterfejs użytkownika\fP:
.IP "  \(bu" 4
\fC\fBui_DatabaseConfigDialog\&.h\fP\fP: Plik generowany przez Qt Designer\&.
.PP

.IP "\(bu" 2
\fBZasoby\fP:
.IP "  \(bu" 4
Pliki QSS (\fC:/styles/amiga\&.qss\fP, \fC:/styles/atari8bit\&.qss\fP, \fC:/styles/zxspectrum\&.qss\fP, \fC:/styles/default\&.qss\fP)\&.
.IP "  \(bu" 4
Czcionki (\fC:/fonts/topaz\&.ttf\fP, \fC:/fonts/zxspectrum\&.ttf\fP, \fC:/fonts/EightBit Atari-Ataripl\&.ttf\fP)\&.
.PP

.PP
.SH "Uwagi"
.PP
.IP "\(bu" 2
Kod nie został zmodyfikowany, zgodnie z wymaganiami użytkownika\&.
.IP "\(bu" 2
Ustawienia są zapisywane w pliku \fCinwentaryzacja\&.ini\fP w katalogu aplikacji\&.
.IP "\(bu" 2
W przypadku błędów ładowania zasobów (np\&. czcionek lub QSS) aplikacja przechodzi na domyślne ustawienia i loguje ostrzeżenia\&.
.IP "\(bu" 2
Czcionki są odrejestrowywane w destruktorze, aby zapobiec wyciekom pamięci\&. 
.PP

