.TH "md_documentation_photoitem_h" 3 "So, 3 maj 2025" "Version 1.1.2" "Inwentaryzacja" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_documentation_photoitem_h \- Dokumentacja dla pliku \fC\fBphotoitem\&.h\fP\fP 

.SH "Metadane"
.PP
.IP "\(bu" 2
\fBPlik\fP: \fBphotoitem\&.h\fP
.IP "\(bu" 2
\fBWersja\fP: 1\&.2\&.2
.IP "\(bu" 2
\fBData\fP: 2025-05-03
.IP "\(bu" 2
\fBAutorzy\fP: Stowarzyszenie Miłośników Oldschoolowych Komputerów SMOK & ChatGPT & GROK
.PP
.SH "Przegląd"
.PP
Plik \fC\fBphotoitem\&.h\fP\fP definiuje klasę \fC\fBPhotoItem\fP\fP, która reprezentuje interaktywny element graficzny (miniaturę zdjęcia) w scenie graficznej Qt (używany w \fCQGraphicsView\fP)\&. Klasa rozszerza \fCQGraphicsPixmapItem\fP o obsługę zdarzeń myszy (kliknięcia, podwójne kliknięcia) i hover (najechanie, opuszczenie kursora), a także wizualne zaznaczanie za pomocą czerwonej ramki\&. Dzięki dziedziczeniu po \fCQObject\fP, umożliwia emisję sygnałów (\fCclicked\fP, \fCdoubleClicked\fP, \fChovered\fP, \fCunhovered\fP), co pozwala na integrację z logiką aplikacji, np\&. z klasą \fC\fBMainWindow\fP\fP w aplikacji inwentaryzacyjnej\&.
.SH "Struktura kodu"
.PP
Plik nagłówkowy zawiera następujące elementy:
.PP
.IP "1." 4
\fBDeklaracja klasy \fC\fBPhotoItem\fP\fP\fP 
.br
.IP "  \(bu" 4
Dziedziczy po \fCQObject\fP i \fCQGraphicsPixmapItem\fP\&.
.IP "  \(bu" 4
Używa makra \fCQ_OBJECT\fP dla wsparcia mechanizmu sygnałów i slotów Qt\&.
.PP

.IP "2." 4
\fBMetody publiczne\fP 
.br
.IP "  \(bu" 4
Konstruktor: Inicjalizuje obiekt, ramkę graficzną i włącza zdarzenia hover\&.
.IP "  \(bu" 4
Destruktor: Zwalnia zasoby ramki\&.
.IP "  \(bu" 4
\fCsetSelected\fP: Ustawia stan zaznaczenia (wyświetla/ukrywa ramkę)\&.
.PP

.IP "3." 4
\fBSygnały\fP 
.br
.IP "  \(bu" 4
\fCclicked\fP: Emitowany po kliknięciu (np\&. prawym przyciskiem) dla wyboru/podglądu zdjęcia\&.
.IP "  \(bu" 4
\fCdoubleClicked\fP: Emitowany po podwójnym kliknięciu (lewym przyciskiem) dla pełnoekranowego podglądu\&.
.IP "  \(bu" 4
\fChovered\fP: Emitowany po najechaniu kursorem na miniaturę\&.
.IP "  \(bu" 4
\fCunhovered\fP: Emitowany po opuszczeniu miniatury kursorem\&.
.PP

.IP "4." 4
\fBMetody chronione\fP 
.br
.IP "  \(bu" 4
\fCmousePressEvent\fP: Obsługuje kliknięcia myszą\&.
.IP "  \(bu" 4
\fCmouseDoubleClickEvent\fP: Obsługuje podwójne kliknięcia\&.
.IP "  \(bu" 4
\fChoverEnterEvent\fP: Obsługuje najechanie kursorem\&.
.IP "  \(bu" 4
\fChoverLeaveEvent\fP: Obsługuje opuszczenie kursora\&.
.PP

.IP "5." 4
\fBMetody prywatne\fP 
.br
.IP "  \(bu" 4
\fCupdateFrame\fP: Aktualizuje wygląd ramki zaznaczenia\&.
.PP

.IP "6." 4
\fBZmienne prywatne\fP 
.br
.IP "  \(bu" 4
\fCm_pressed\fP: Flaga kliknięcia (obecnie nieużywana)\&.
.IP "  \(bu" 4
\fCm_selected\fP: Flaga zaznaczenia (kontroluje ramkę)\&.
.IP "  \(bu" 4
\fCm_frame\fP: Obiekt \fCQGraphicsRectItem\fP dla ramki zaznaczenia\&.
.PP

.PP
.SH "Opis działania"
.PP
.IP "\(bu" 2
\fBInicjalizacja\fP: Konstruktor tworzy obiekt jako element graficzny (\fCQGraphicsPixmapItem\fP) i obiekt sygnałowy (\fCQObject\fP), ustawia flagi \fCm_pressed\fP i \fCm_selected\fP na \fCfalse\fP, tworzy ramkę (\fCm_frame\fP) jako dziecko, włącza zdarzenia hover i konfiguruje ramkę jako niewidoczną\&.
.IP "\(bu" 2
\fBInterfejs graficzny\fP: Wyświetla miniaturę zdjęcia (np\&. 80x80 pikseli w \fC\fBMainWindow\fP\fP) w \fCQGraphicsView\fP, z możliwością zaznaczenia czerwoną ramką o szerokości 2 piksele\&.
.IP "\(bu" 2
\fBInterakcje\fP:
.IP "  \(bu" 4
\fBKliknięcia\fP: Prawe kliknięcie emituje \fCclicked\fP (np\&. dla podglądu), lewe jest przekazywane dla podwójnego kliknięcia\&.
.IP "  \(bu" 4
\fBPodwójne kliknięcia\fP: Lewe podwójne kliknięcie emituje \fCdoubleClicked\fP (np\&. dla pełnego ekranu)\&.
.IP "  \(bu" 4
\fBHover\fP: Najechanie emituje \fChovered\fP, opuszczenie \fCunhovered\fP (np\&. dla podświetlenia)\&.
.PP

.IP "\(bu" 2
\fBZaznaczenie\fP: Metoda \fCsetSelected\fP włącza/wyłącza czerwoną ramkę poprzez \fCupdateFrame\fP, co jest używane w \fC\fBMainWindow\fP\fP do wskazywania wybranego zdjęcia\&.
.IP "\(bu" 2
\fBIntegracja\fP: Sygnały są podłączane w \fC\fBMainWindow\fP\fP do slotów, np\&. \fConPhotoClicked\fP, dla wyboru lub podglądu zdjęcia\&.
.PP
.SH "Zależności"
.PP
.IP "\(bu" 2
\fBBiblioteki Qt\fP:
.IP "  \(bu" 4
\fCQGraphicsPixmapItem\fP, \fCQObject\fP, \fCQGraphicsRectItem\fP, \fCQGraphicsSceneHoverEvent\fP, \fCQGraphicsSceneMouseEvent\fP: Obsługa grafiki, sygnałów i zdarzeń\&.
.PP

.IP "\(bu" 2
\fBNagłówki aplikacji\fP:
.IP "  \(bu" 4
Brak zależności od innych nagłówków aplikacji (np\&. \fC\fBmainwindow\&.h\fP\fP)\&.
.PP

.IP "\(bu" 2
\fBZasoby\fP:
.IP "  \(bu" 4
Brak bezpośrednich zależności od zasobów Qt (np\&. QSS, czcionek)\&.
.PP

.PP
.SH "Uwagi"
.PP
.IP "\(bu" 2
Kod nie został zmodyfikowany, zgodnie z wymaganiami użytkownika\&.
.IP "\(bu" 2
Klasa jest kluczowym elementem dla interaktywnych miniatur zdjęć w \fC\fBMainWindow\fP\fP\&.
.IP "\(bu" 2
Flaga \fCm_pressed\fP jest zdefiniowana, ale nieużywana, co sugeruje możliwość przyszłych rozszerzeń (np\&. obsługa przeciągania)\&.
.IP "\(bu" 2
Sygnały \fChovered\fP i \fCunhovered\fP nie są obecnie wykorzystywane w \fC\fBMainWindow\fP\fP, ale mogą służyć do podświetlania lub tooltipów\&.
.IP "\(bu" 2
Ramka zaznaczenia jest prosta (czerwona, 2 piksele), ale może być dostosowana (np\&. kolor, styl) w przyszłych wersjach\&. 
.PP

