.TH "md_documentation_fullscreenphotoviewer_h" 3 "So, 3 maj 2025" "Version 1.1.2" "Inwentaryzacja" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_documentation_fullscreenphotoviewer_h \- Dokumentacja dla pliku \fC\fBfullscreenphotoviewer\&.h\fP\fP 

.SH "Metadane"
.PP
.IP "\(bu" 2
\fBPlik\fP: \fBfullscreenphotoviewer\&.h\fP
.IP "\(bu" 2
\fBWersja\fP: 1\&.2\&.2
.IP "\(bu" 2
\fBData\fP: 2025-05-03
.IP "\(bu" 2
\fBAutorzy\fP: Stowarzyszenie Miłośników Oldschoolowych Komputerów SMOK & ChatGPT & GROK
.PP
.SH "Przegląd"
.PP
Plik \fC\fBfullscreenphotoviewer\&.h\fP\fP definiuje dwie klasy: \fC\fBZoomableGraphicsView\fP\fP oraz \fC\fBFullScreenPhotoViewer\fP\fP, używane w aplikacji inwentaryzacyjnej do pełnoekranowego podglądu zdjęć eksponatów\&. \fC\fBZoomableGraphicsView\fP\fP umożliwia powiększanie i przesuwanie obrazu za pomocą kółka myszy i przeciągania, natomiast \fC\fBFullScreenPhotoViewer\fP\fP tworzy bezramkowe, modalne okno pełnoekranowe z możliwością zamknięcia klawiszem Escape\&.
.SH "Struktura kodu"
.PP
Plik nagłówkowy zawiera następujące elementy:
.PP
.IP "1." 4
\fBDeklaracja klasy \fC\fBZoomableGraphicsView\fP\fP\fP 
.br
.IP "  \(bu" 4
Dziedziczy po \fCQGraphicsView\fP\&.
.IP "  \(bu" 4
Metody:
.IP "    \(bu" 6
Konstruktor: Inicjalizuje widok z trybem przeciągania i kotwicą transformacji\&.
.IP "    \(bu" 6
\fCwheelEvent\fP: Obsługuje powiększanie/pomniejszanie obrazu kółkiem myszy\&.
.PP

.IP "  \(bu" 4
Zmienna: \fCm_scaleFactor\fP (bieżący współczynnik skali)\&.
.PP

.IP "2." 4
\fBDeklaracja klasy \fC\fBFullScreenPhotoViewer\fP\fP\fP 
.br
.IP "  \(bu" 4
Dziedziczy po \fCQMainWindow\fP\&.
.IP "  \(bu" 4
Metody:
.IP "    \(bu" 6
Konstruktor: Inicjalizuje okno pełnoekranowe, ustawia zdjęcie i widok\&.
.IP "    \(bu" 6
\fCkeyPressEvent\fP: Obsługuje zamykanie okna klawiszem Escape\&.
.PP

.IP "  \(bu" 4
Zmienne: \fCm_scene\fP (scena graficzna), \fCm_view\fP (widok \fBZoomableGraphicsView\fP)\&.
.PP

.IP "3." 4
\fBMetody inline\fP 
.br
.IP "  \(bu" 4
Wszystkie metody są zdefiniowane w pliku nagłówkowym, co eliminuje potrzebę osobnego pliku \&.cpp\&.
.PP

.PP
.SH "Opis działania"
.PP
.IP "1." 4
\fB\fBZoomableGraphicsView\fP\fP:
.IP "  \(bu" 4
\fBInicjalizacja\fP: Ustawia kotwicę transformacji pod kursorem myszy (\fCAnchorUnderMouse\fP) i tryb przeciągania (\fCScrollHandDrag\fP), umożliwiając intuicyjne powiększanie i przesuwanie obrazu\&.
.IP "  \(bu" 4
\fBPowiększanie\fP: Kółko myszy zwiększa skalę o 1\&.15 (zoom in) lub zmniejsza o 1/1\&.15 (zoom out)\&. Współczynnik skali jest aktualizowany w zmiennej \fCm_scaleFactor\fP\&.
.IP "  \(bu" 4
\fBPrzesuwanie\fP: Tryb ScrollHandDrag pozwala na przesuwanie obrazu przez przeciąganie myszą\&.
.PP

.IP "2." 4
\fB\fBFullScreenPhotoViewer\fP\fP:
.IP "  \(bu" 4
\fBInicjalizacja\fP: Tworzy bezramkowe okno pełnoekranowe z flagami \fCFramelessWindowHint\fP i \fCWindowStaysOnTopHint\fP\&. Ustawia modalność (\fCApplicationModal\fP) i automatyczne usuwanie po zamknięciu (\fCWA_DeleteOnClose\fP)\&.
.IP "  \(bu" 4
\fBWyświetlanie zdjęcia\fP: Zdjęcie (\fCQPixmap\fP) jest dodawane do sceny graficznej (\fCQGraphicsScene\fP), która jest wyświetlana w \fC\fBZoomableGraphicsView\fP\fP ustawionym jako centralny widget\&.
.IP "  \(bu" 4
\fBZamykanie\fP: Okno zamyka się po naciśnięciu klawisza Escape, co jest obsługiwane w metodzie \fCkeyPressEvent\fP\&.
.PP

.PP
.SH "Zależności"
.PP
.IP "\(bu" 2
\fBBiblioteki Qt\fP:
.IP "  \(bu" 4
\fCQMainWindow\fP: Bazowa klasa dla okna pełnoekranowego\&.
.IP "  \(bu" 4
\fCQGraphicsView\fP, \fCQGraphicsScene\fP: Obsługa widoku i sceny graficznej\&.
.IP "  \(bu" 4
\fCQKeyEvent\fP, \fCQWheelEvent\fP: Obsługa zdarzeń klawiatury i kółka myszy\&.
.PP

.IP "\(bu" 2
\fBZasoby\fP:
.IP "  \(bu" 4
Brak bezpośrednich zależności od zasobów Qt (np\&. QSS, czcionek)\&.
.PP

.PP
.SH "Uwagi"
.PP
.IP "\(bu" 2
Kod nie został zmodyfikowany, zgodnie z wymaganiami użytkownika\&.
.IP "\(bu" 2
Implementacja inline w pliku nagłówkowym zapewnia prostotę i wydajność\&.
.IP "\(bu" 2
\fC\fBFullScreenPhotoViewer\fP\fP jest modalny, co blokuje interakcję z innymi oknami aplikacji podczas wyświetlania zdjęcia\&.
.IP "\(bu" 2
Automatyczne usuwanie po zamknięciu (\fCWA_DeleteOnClose\fP) zapobiega wyciekom pamięci\&. 
.PP

