.TH "md_documentation_main" 3 "So, 3 maj 2025" "Version 1.1.2" "Inwentaryzacja" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_documentation_main \- Dokumentacja dla pliku \fC\fBmain\&.cpp\fP\fP 

.SH "Metadane"
.PP
.IP "\(bu" 2
\fBPlik\fP: \fBmain\&.cpp\fP
.IP "\(bu" 2
\fBWersja\fP: 1\&.2\&.2
.IP "\(bu" 2
\fBData\fP: 2025-05-03
.IP "\(bu" 2
\fBAutorzy\fP: Stowarzyszenie Miłośników Oldschoolowych Komputerów SMOK & ChatGPT & GROK
.PP
.SH "Przegląd"
.PP
Plik \fC\fBmain\&.cpp\fP\fP jest głównym punktem wejścia aplikacji inwentaryzacyjnej opartej na bibliotece Qt\&. Odpowiada za inicjalizację aplikacji, ustawienie jej podstawowych właściwości (nazwa, wersja, ikona), ładowanie tłumaczeń językowych, wyświetlanie okna konfiguracji bazy danych oraz nawiązywanie połączenia z wybraną bazą danych (SQLite lub MySQL)\&. Po poprawnym skonfigurowaniu środowiska uruchamia główne okno aplikacji reprezentowane przez klasę \fC\fBitemList\fP\fP\&.
.SH "Struktura kodu"
.PP
Kod jest zorganizowany w następujące sekcje funkcjonalne:
.PP
.IP "1." 4
\fBInicjalizacja aplikacji Qt\fP 
.br
.IP "  \(bu" 4
Tworzy instancję \fCQApplication\fP i ustawia styl graficzny 'Fusion' dla spójnego wyglądu\&.
.IP "  \(bu" 4
Ustawia nazwę aplikacji ('Inwentaryzacja') i wersję (1\&.2\&.2)\&.
.IP "  \(bu" 4
Ładuje i ustawia ikonę aplikacji z zasobów Qt (\fC:/images/icon\&.png\fP)\&.
.PP

.IP "2." 4
\fBŁadowanie tłumaczeń\fP 
.br
.IP "  \(bu" 4
Wczytuje tłumaczenia językowe na podstawie języka systemowego użytkownika\&.
.IP "  \(bu" 4
Pliki tłumaczeń (\fCInwentaryzacja_*\&.qm\fP) znajdują się w zasobach Qt (\fC:/i18n/\fP)\&.
.IP "  \(bu" 4
Po znalezieniu odpowiedniego pliku tłumaczenia, instaluje go w aplikacji\&.
.PP

.IP "3." 4
\fBKonfiguracja bazy danych\fP 
.br
.IP "  \(bu" 4
Wyświetla okno dialogowe \fC\fBDatabaseConfigDialog\fP\fP, w którym użytkownik wybiera typ bazy danych (SQLite lub MySQL) i wprowadza parametry połączenia\&.
.IP "  \(bu" 4
Jeśli użytkownik anuluje konfigurację, aplikacja kończy działanie\&.
.PP

.IP "4." 4
\fBNawiązywanie połączenia z bazą danych\fP 
.br
.IP "  \(bu" 4
Pobiera wybrany typ bazy danych i odpowiednie parametry z \fC\fBDatabaseConfigDialog\fP\fP\&.
.IP "  \(bu" 4
Obsługuje dwa typy baz danych:
.IP "    \(bu" 6
\fBSQLite\fP: Sprawdza ścieżkę do pliku bazy i wywołuje funkcję \fCsetupDatabase\fP z parametrem ścieżki\&.
.IP "    \(bu" 6
\fBMySQL\fP: Przekazuje dane dostępowe (host, nazwa bazy, użytkownik, hasło, port) do funkcji \fCsetupDatabase\fP\&.
.PP

.IP "  \(bu" 4
Loguje błędy w przypadku niepoprawnego typu bazy danych lub nieudanego połączenia\&.
.PP

.IP "5." 4
\fBUruchamianie głównego okna\fP 
.br
.IP "  \(bu" 4
Tworzy i wyświetla główne okno aplikacji (\fC\fBitemList\fP\fP), które zawiera interfejs użytkownika do zarządzania inwentaryzacją\&.
.PP

.IP "6." 4
\fBPętla zdarzeń Qt\fP 
.br
.IP "  \(bu" 4
Uruchamia główną pętlę zdarzeń Qt za pomocą \fCQApplication::exec()\fP, obsługującą interakcje użytkownika i zdarzenia systemowe\&.
.PP

.PP
.SH "Opis działania"
.PP
.IP "1." 4
\fBInicjalizacja\fP: Po uruchomieniu aplikacji tworzona jest instancja \fCQApplication\fP, która zarządza cyklem życia aplikacji Qt\&. Styl 'Fusion' zapewnia spójny wygląd na różnych platformach\&.
.IP "2." 4
\fBTłumaczenia\fP: Aplikacja próbuje załadować tłumaczenia na podstawie języka systemowego, co umożliwia lokalizację interfejsu użytkownika\&.
.IP "3." 4
\fBKonfiguracja bazy danych\fP: Użytkownik musi skonfigurować połączenie z bazą danych za pomocą okna \fC\fBDatabaseConfigDialog\fP\fP\&. Jeśli konfiguracja zostanie anulowana, aplikacja kończy działanie\&.
.IP "4." 4
\fBPołączenie z bazą danych\fP: Funkcja \fCsetupDatabase\fP (zdefiniowana w \fC\fButils\&.h\fP\fP) jest wywoływana z odpowiednimi parametrami w zależności od typu bazy danych\&. W przypadku niepowodzenia aplikacja kończy działanie\&.
.IP "5." 4
\fBGłówne okno\fP: Po pomyślnym połączeniu z bazą danych wyświetlane jest główne okno aplikacji, które umożliwia użytkownikowi interakcję z danymi inwentaryzacyjnymi\&.
.IP "6." 4
\fBPętla zdarzeń\fP: Aplikacja przechodzi w tryb oczekiwania na zdarzenia użytkownika, takie jak kliknięcia czy wprowadzanie danych\&.
.PP
.SH "Zależności"
.PP
.IP "\(bu" 2
\fBBiblioteki Qt\fP:
.IP "  \(bu" 4
\fCQApplication\fP: Zarządzanie aplikacją i cyklem zdarzeń\&.
.IP "  \(bu" 4
\fCQCoreApplication\fP: Ustawianie metadanych aplikacji\&.
.IP "  \(bu" 4
\fCQDebug\fP: Logowanie komunikatów diagnostycznych\&.
.IP "  \(bu" 4
\fCQDirIterator\fP: (Nieużywane wprost, ale włączone w pliku)\&.
.IP "  \(bu" 4
\fCQTranslator\fP: Obsługa tłumaczeń językowych\&.
.IP "  \(bu" 4
\fCQIcon\fP: Ustawianie ikony aplikacji\&.
.PP

.IP "\(bu" 2
\fBNagłówki aplikacji\fP:
.IP "  \(bu" 4
\fC\fBDatabaseConfigDialog\&.h\fP\fP: Okno konfiguracji bazy danych\&.
.IP "  \(bu" 4
\fC\fBitemList\&.h\fP\fP: Główne okno aplikacji\&.
.IP "  \(bu" 4
\fC\fButils\&.h\fP\fP: Funkcje pomocnicze, w tym \fCsetupDatabase\fP\&.
.PP

.IP "\(bu" 2
\fBZasoby\fP:
.IP "  \(bu" 4
Ikona aplikacji (\fC:/images/icon\&.png\fP)\&.
.IP "  \(bu" 4
Pliki tłumaczeń (\fC:/i18n/Inwentaryzacja_*\&.qm\fP)\&.
.PP

.PP
.SH "Uwagi"
.PP
.IP "\(bu" 2
Kod nie został zmodyfikowany, zgodnie z wymaganiami użytkownika\&.
.IP "\(bu" 2
Aplikacja wymaga poprawnego skonfigurowania bazy danych, aby przejść do głównego okna\&.
.IP "\(bu" 2
Styl graficzny i czcionki są zarządzane przez \fC\fBDatabaseConfigDialog\fP\fP po zatwierdzeniu ustawień\&.
.IP "\(bu" 2
W przypadku błędów (np\&. brak pliku SQLite lub niepoprawny typ bazy danych) aplikacja loguje komunikaty za pomocą \fCqDebug\fP i kończy działanie\&.
.PP
.SH "Wartości zwracane"
.PP
.IP "\(bu" 2
\fB0\fP: Aplikacja zakończyła się pomyślnie lub użytkownik anulował konfigurację\&.
.IP "\(bu" 2
\fBInne\fP: Błąd podczas nawiązywania połączenia z bazą danych lub nieznany typ bazy danych\&. 
.PP

