.TH "md_documentation_utils_cpp" 3 "So, 3 maj 2025" "Version 1.1.2" "Inwentaryzacja" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_documentation_utils_cpp \- Dokumentacja dla pliku \fC\fButils\&.cpp\fP\fP 

.SH "Metadane"
.PP
.IP "\(bu" 2
\fBPlik\fP: \fButils\&.cpp\fP
.IP "\(bu" 2
\fBWersja\fP: 1\&.2\&.2
.IP "\(bu" 2
\fBData\fP: 2025-05-03
.IP "\(bu" 2
\fBAutorzy\fP: Stowarzyszenie Miłośników Oldschoolowych Komputerów SMOK & ChatGPT & GROK
.PP
.SH "Przegląd"
.PP
Plik \fC\fButils\&.cpp\fP\fP zawiera implementację funkcji \fCsetupDatabase\fP, która konfiguruje i otwiera połączenie z bazą danych SQLite lub MySQL w aplikacji inwentaryzacyjnej\&. Funkcja rejestruje połączenie pod nazwą 'default_connection', używaną przez inne komponenty aplikacji (np\&. \fC\fBMainWindow\fP\fP, \fCtypes\fP, \fCstatus\fP)\&. Dla SQLite automatycznie tworzy schemat bazy danych (tabele i dane początkowe), co zapewnia gotowość bazy do pracy po pierwszym uruchomieniu\&.
.SH "Struktura kodu"
.PP
Kod jest podzielony na następujące sekcje:
.PP
.IP "1." 4
\fBSekcja implementacji funkcji \fCsetupDatabase\fP\fP 
.br
.IP "  \(bu" 4
Konfiguruje połączenie, otwiera bazę i obsługuje błędy\&.
.IP "  \(bu" 4
Dla SQLite tworzy schemat bazy i przykładowe dane\&.
.PP

.IP "2." 4
\fBSekcja tworzenia schematu SQLite\fP 
.br
.IP "  \(bu" 4
Definiuje tabele: \fCeksponaty\fP, \fCtypes\fP, \fCvendors\fP, \fCmodels\fP, \fCstatuses\fP, \fCstorage_places\fP, \fCphotos\fP\&.
.IP "  \(bu" 4
Wypełnia tabele słownikowe przykładowymi danymi (np\&. 'Komputer', 'Atari', 'Sprawny')\&.
.PP

.PP
.SH "Opis działania"
.PP
.IP "1." 4
\fBInicjalizacja połączenia\fP:
.IP "  \(bu" 4
Usuwa istniejące połączenie 'default_connection' (\fCQSqlDatabase::removeDatabase\fP)\&.
.IP "  \(bu" 4
Tworzy nowe połączenie z driverem \fCQSQLITE\fP (dla \fCdbType='SQLite3'\fP) lub \fCQMYSQL\fP (dla \fCdbType='MySQL'\fP)\&.
.IP "  \(bu" 4
Konfiguruje parametry:
.IP "    \(bu" 6
\fBMySQL\fP: Ustawia \fChost\fP, \fCdbSource\fP (nazwa bazy), \fCuser\fP, \fCpassword\fP, \fCport\fP\&.
.IP "    \(bu" 6
\fBSQLite\fP: Ustawia \fCdbSource\fP jako ścieżkę do pliku bazy\&.
.PP

.IP "  \(bu" 4
Próbuje otworzyć połączenie, wyświetlając \fCQMessageBox\fP z błędem w przypadku niepowodzenia\&.
.PP

.IP "2." 4
\fBTworzenie schematu dla SQLite\fP:
.IP "  \(bu" 4
Sprawdza, czy wszystkie wymagane tabele (\fCeksponaty\fP, \fCtypes\fP, \fCvendors\fP, \fCmodels\fP, \fCstatuses\fP, \fCstorage_places\fP, \fCphotos\fP) istnieją\&.
.IP "  \(bu" 4
Jeśli brakuje którejkolwiek tabeli, wykonuje zapytania SQL:
.IP "    \(bu" 6
\fBTabela \fCeksponaty\fP\fP: Przechowuje dane eksponatów (np\&. nazwa, typ, producent, status)\&.
.IP "    \(bu" 6
\fBTabele słownikowe\fP (\fCtypes\fP, \fCvendors\fP, \fCmodels\fP, \fCstatuses\fP, \fCstorage_places\fP): Przechowują unikalne nazwy z UUID jako kluczem\&.
.IP "    \(bu" 6
\fBTabela \fCphotos\fP\fP: Przechowuje zdjęcia powiązane z eksponatami (BLOB)\&.
.PP

.IP "  \(bu" 4
Wypełnia tabele słownikowe przykładowymi danymi:
.IP "    \(bu" 6
Typy: 'Komputer', 'Monitor', 'Kabel'\&.
.IP "    \(bu" 6
Producenci: 'Atari', 'Commodore', 'Sinclair'\&.
.IP "    \(bu" 6
Modele: 'Atari 800XL', 'Amiga 500', 'ZX Spectrum'\&.
.IP "    \(bu" 6
Statusy: 'Sprawny', 'Uszkodzony', 'W naprawie'\&.
.IP "    \(bu" 6
Miejsce przechowywania: 'Magazyn 1', 'Półka B3'\&.
.PP

.IP "  \(bu" 4
Używa \fCQUuid\fP do generowania unikalnych identyfikatorów\&.
.PP

.IP "3." 4
\fBZwracana wartość\fP:
.IP "  \(bu" 4
Zwraca \fCtrue\fP po pomyślnym nawiązaniu połączenia i (dla SQLite) utworzeniu schematu\&.
.IP "  \(bu" 4
Zwraca \fCfalse\fP w przypadku błędu połączenia\&.
.PP

.PP
.SH "Zależności"
.PP
.IP "\(bu" 2
\fBBiblioteki Qt\fP:
.IP "  \(bu" 4
\fCQMessageBox\fP: Wyświetlanie błędów połączenia\&.
.IP "  \(bu" 4
\fCQSqlDatabase\fP, \fCQSqlError\fP, \fCQSqlQuery\fP: Obsługa połączenia i zapytań SQL\&.
.IP "  \(bu" 4
\fCQUuid\fP: Generowanie unikalnych identyfikatorów\&.
.PP

.IP "\(bu" 2
\fBNagłówki aplikacji\fP:
.IP "  \(bu" 4
Brak zależności od innych nagłówków aplikacji (tylko Qt)\&.
.PP

.IP "\(bu" 2
\fBZasoby\fP:
.IP "  \(bu" 4
Brak bezpośrednich zależności od zasobów Qt (np\&. QSS, czcionek)\&.
.PP

.PP
.SH "Uwagi"
.PP
.IP "\(bu" 2
Kod nie został zmodyfikowany, zgodnie z wymaganiami użytkownika\&.
.IP "\(bu" 2
Funkcja \fCsetupDatabase\fP jest centralnym elementem konfiguracji bazy danych, używanym przez inne komponenty aplikacji\&.
.IP "\(bu" 2
Dla SQLite automatyczne tworzenie schematu i danych początkowych zapewnia gotowość bazy, ale brak podobnego mechanizmu dla MySQL (zakłada, że schemat już istnieje)\&.
.IP "\(bu" 2
Schemat bazy używa UUID jako kluczy głównych, co zapewnia unikalność, ale operacje CRUD w innych klasach (np\&. \fCtypes\fP, \fCstatus\fP) opierają się na nazwach, co może powodować problemy przy duplikatach\&.
.IP "\(bu" 2
Połączenie 'default_connection' jest współdzielone, co wymaga ostrożnego zarządzania w przypadku wielokrotnego wywoływania funkcji\&.
.IP "\(bu" 2
Przykładowe dane są zorientowane na retro sprzęt komputerowy, co odzwierciedla kontekst aplikacji\&. 
.PP

