.TH "models" 3 "So, 3 maj 2025" "Version 1.1.2" "Inwentaryzacja" \" -*- nroff -*-
.ad l
.nh
.SH NAME
models \- Okno dialogowe do zarządzania modelami eksponatów\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <models\&.h>\fP
.PP
Dziedziczy QDialog\&.
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "\fBmodels\fP (QWidget *parent=nullptr)"
.br
.RI "Konstruktor klasy models\&. "
.ti -1c
.RI "\fB~models\fP ()"
.br
.RI "Destruktor klasy models\&. "
.ti -1c
.RI "void \fBsetMainWindow\fP (\fBMainWindow\fP *mainWindow)"
.br
.RI "Ustawia wskaźnik na główne okno aplikacji\&. "
.ti -1c
.RI "void \fBsetVendorId\fP (const QString &vendorId)"
.br
.RI "Ustawia identyfikator producenta dla modeli\&. "
.in -1c
.SH "Opis szczegółowy"
.PP 
Okno dialogowe do zarządzania modelami eksponatów\&. 


.SH "ClassOverview"
.PP
Klasa models dziedziczy po QDialog i zapewnia interfejs do dodawania, edytowania i usuwania modeli eksponatów w bazie danych\&. Współpracuje z klasą \fBMainWindow\fP, aby odświeżyć listę modeli w combo boxie po zapisaniu zmian\&. Używa QString jako typu dla identyfikatora producenta (vendorId)\&.
.SH "Responsibilities"
.PP
.IP "\(bu" 2
Wyświetlanie listy modeli w QListView\&.
.IP "\(bu" 2
Dodawanie nowych modeli do tabeli 'models' z powiązaniem do producenta\&.
.IP "\(bu" 2
Edycja istniejących modeli (zmiana nazwy)\&.
.IP "\(bu" 2
Usuwanie modeli po potwierdzeniu użytkownika\&.
.IP "\(bu" 2
Odświeżanie combo boxa modeli w \fBMainWindow\fP po zapisaniu zmian\&. 
.PP

.SH "Dokumentacja konstruktora i destruktora"
.PP 
.SS "models::models (QWidget * parent = \fCnullptr\fP)\fC [explicit]\fP"

.PP
Konstruktor klasy models\&. 
.PP
\fBParametry\fP
.RS 4
\fIparent\fP Wskaźnik na nadrzędny widget\&. Domyślnie nullptr\&.
.RE
.PP
.SH "ConstructorOverview"
.PP
Inicjalizuje okno dialogowe, konfiguruje interfejs użytkownika, ustanawia połączenie z bazą danych i podłącza sloty dla przycisków\&.
.PP
\fBParametry\fP
.RS 4
\fIparent\fP Wskaźnik na nadrzędny widget (domyślnie nullptr)\&.
.RE
.PP
.SH "ConstructorOverview"
.PP
Inicjalizuje interfejs graficzny, ustawia tytuł okna, nawiązuje połączenie z bazą danych ('default_connection'), podłącza sloty dla przycisków (dodaj, edytuj, usuń, OK, Anuluj) i odświeża listę modeli w QListView\&. 
.SS "models::~models ()"

.PP
Destruktor klasy models\&. 
.SH "DestructorOverview"
.PP
Zwalnia zasoby interfejsu użytkownika i usuwa obiekty dynamiczne\&.
.SH "DestructorOverview"
.PP
Usuwa obiekt interfejsu użytkownika i zwalnia zasoby\&. 
.SH "Dokumentacja funkcji składowych"
.PP 
.SS "void models::setMainWindow (\fBMainWindow\fP * mainWindow)"

.PP
Ustawia wskaźnik na główne okno aplikacji\&. 
.PP
\fBParametry\fP
.RS 4
\fImainWindow\fP Wskaźnik na obiekt \fBMainWindow\fP\&.
.RE
.PP
.SH "MethodOverview"
.PP
Umożliwia komunikację z głównym oknem w celu odświeżenia listy modeli w combo boxie po zapisaniu zmian\&.
.PP
\fBParametry\fP
.RS 4
\fImainWindow\fP Wskaźnik na obiekt \fBMainWindow\fP\&.
.RE
.PP
.SH "MethodOverview"
.PP
Przechowuje referencję do \fBMainWindow\fP, umożliwiając odświeżanie combo boxa modeli po zapisaniu zmian\&. 
.SS "void models::setVendorId (const QString & vendorId)"

.PP
Ustawia identyfikator producenta dla modeli\&. Ustawia identyfikator producenta, powiązany z modelami\&.
.PP
\fBParametry\fP
.RS 4
\fIvendorId\fP QString zawierający identyfikator producenta (np\&. UUID)\&.
.RE
.PP
.SH "MethodOverview"
.PP
Ogranicza listę modeli do tych powiązanych z podanym producentem i ustala vendorId dla nowych modeli\&.
.PP
\fBParametry\fP
.RS 4
\fIvendorId\fP QString zawierający identyfikator producenta (np\&. UUID)\&.
.RE
.PP
.SH "MethodOverview"
.PP
Ustawia vendorId dla nowych modeli, używane podczas dodawania modelu w metodzie onAddClicked\&. 

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Inwentaryzacja\&.
