.TH "include/photoitem.h" 3 "So, 3 maj 2025" "Version 1.1.2" "Inwentaryzacja" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/photoitem.h \- Deklaracja klasy \fBPhotoItem\fP reprezentującej interaktywny element graficzny zdjęcia\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <QGraphicsPixmapItem>\fP
.br
\fC#include <QGraphicsRectItem>\fP
.br
\fC#include <QGraphicsSceneHoverEvent>\fP
.br
\fC#include <QGraphicsSceneMouseEvent>\fP
.br
\fC#include <QObject>\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBPhotoItem\fP"
.br
.RI "Element graficzny reprezentujący zdjęcie z obsługą zaznaczenia i zdarzeń interaktywnych\&. "
.in -1c
.SH "Opis szczegółowy"
.PP 
Deklaracja klasy \fBPhotoItem\fP reprezentującej interaktywny element graficzny zdjęcia\&. 


.PP
\fBAutor\fP
.RS 4
Stowarzyszenie Miłośników Oldschoolowych Komputerów SMOK & ChatGPT & GROK 
.RE
.PP
\fBWersja\fP
.RS 4
1\&.2\&.2 
.RE
.PP
\fBData\fP
.RS 4
2025-05-03
.RE
.PP
.SH "Overview"
.PP
Plik zawiera deklarację klasy \fBPhotoItem\fP, która rozszerza funkcjonalność QGraphicsPixmapItem o obsługę interakcji użytkownika (kliknięcia, najechanie kursorem, opuszczenie kursora) oraz możliwość wizualnego zaznaczenia elementu za pomocą ramki\&. Klasa jest używana w aplikacji inwentaryzacyjnej do wyświetlania miniatur zdjęć eksponatów w QGraphicsView\&.
.SH "Structure"
.PP
Plik nagłówkowy zawiera:
.IP "1." 4
\fBDeklarację klasy \fBPhotoItem\fP\fP – dziedziczy po QObject i QGraphicsPixmapItem\&.
.IP "2." 4
\fBMetody publiczne\fP – konstruktor, destruktor, ustawianie zaznaczenia\&.
.IP "3." 4
\fBSygnały\fP – emitowane dla kliknięć, podwójnych kliknięć i zdarzeń hover\&.
.IP "4." 4
\fBMetody chronione\fP – obsługa zdarzeń myszy i hover\&.
.IP "5." 4
\fBMetody prywatne\fP – aktualizacja ramki zaznaczenia\&.
.IP "6." 4
\fBZmienne prywatne\fP – flagi stanu i ramka graficzna\&.
.PP
.SH "Dependencies"
.PP
.IP "\(bu" 2
\fBQt Framework\fP: Używa klas QGraphicsPixmapItem, QObject, QGraphicsRectItem, QGraphicsSceneHoverEvent, QGraphicsSceneMouseEvent\&.
.PP
.SH "Notes"
.PP
.IP "\(bu" 2
Kod nie został zmodyfikowany, zgodnie z wymaganiami użytkownika\&. Dodano jedynie komentarze i dokumentację\&.
.IP "\(bu" 2
Klasa jest kluczowym komponentem do interaktywnego wyświetlania miniatur zdjęć w \fBMainWindow\fP\&.
.IP "\(bu" 2
Sygnały umożliwiają integrację z \fBMainWindow\fP dla podglądu zdjęć lub ich usuwania\&. 
.PP

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Inwentaryzacja\&.
