.TH "PhotoItem" 3 "So, 3 maj 2025" "Version 1.1.2" "Inwentaryzacja" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhotoItem \- Element graficzny reprezentujący zdjęcie z obsługą zaznaczenia i zdarzeń interaktywnych\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <photoitem\&.h>\fP
.PP
Dziedziczy QObject i QGraphicsPixmapItem\&.
.SS "Sygnały"

.in +1c
.ti -1c
.RI "void \fBclicked\fP (\fBPhotoItem\fP *item)"
.br
.RI "Sygnał emitowany po jednokrotnym kliknięciu lewym przyciskiem myszy\&. "
.ti -1c
.RI "void \fBdoubleClicked\fP (\fBPhotoItem\fP *item)"
.br
.RI "Sygnał emitowany po dwukrotnym kliknięciu lewym przyciskiem myszy\&. "
.ti -1c
.RI "void \fBhovered\fP (\fBPhotoItem\fP *item)"
.br
.RI "Sygnał emitowany po najechaniu kursorem na obiekt\&. "
.ti -1c
.RI "void \fBunhovered\fP (\fBPhotoItem\fP *item)"
.br
.RI "Sygnał emitowany po opuszczeniu kursora z obiektu\&. "
.in -1c
.SS "Metody publiczne"

.in +1c
.ti -1c
.RI "\fBPhotoItem\fP (QGraphicsItem *parent=nullptr)"
.br
.RI "Konstruktor klasy \fBPhotoItem\fP\&. "
.ti -1c
.RI "\fB~PhotoItem\fP ()"
.br
.RI "Destruktor klasy \fBPhotoItem\fP\&. "
.ti -1c
.RI "void \fBsetSelected\fP (bool selected)"
.br
.RI "Ustawia stan zaznaczenia obiektu\&. "
.in -1c
.SS "Metody chronione"

.in +1c
.ti -1c
.RI "void \fBmousePressEvent\fP (QGraphicsSceneMouseEvent *event) override"
.br
.RI "Obsługa zdarzenia kliknięcia myszy\&. "
.ti -1c
.RI "void \fBmouseDoubleClickEvent\fP (QGraphicsSceneMouseEvent *event) override"
.br
.RI "Obsługa zdarzenia podwójnego kliknięcia myszy\&. "
.ti -1c
.RI "void \fBhoverEnterEvent\fP (QGraphicsSceneHoverEvent *event) override"
.br
.RI "Obsługa zdarzenia najechania kursora\&. "
.ti -1c
.RI "void \fBhoverLeaveEvent\fP (QGraphicsSceneHoverEvent *event) override"
.br
.RI "Obsługa zdarzenia opuszczenia kursora\&. "
.in -1c
.SH "Opis szczegółowy"
.PP 
Element graficzny reprezentujący zdjęcie z obsługą zaznaczenia i zdarzeń interaktywnych\&. 


.SH "ClassOverview"
.PP
Klasa \fBPhotoItem\fP dziedziczy po QGraphicsPixmapItem i QObject, co umożliwia wyświetlanie grafiki na scenie graficznej Qt oraz emitowanie sygnałów Qt\&. Umożliwia reagowanie na kliknięcia i zdarzenia kursora myszy (hover), wizualne oznaczenie zaznaczenia oraz emitowanie sygnałów do logiki aplikacji, np\&. \fBMainWindow\fP, dla podglądu zdjęć lub ich usuwania\&.
.SH "Responsibilities"
.PP
.IP "\(bu" 2
Wyświetlanie miniatury zdjęcia w QGraphicsView\&.
.IP "\(bu" 2
Obsługa kliknięć (pojedynczych i podwójnych) oraz zdarzeń hover\&.
.IP "\(bu" 2
Wizualne zaznaczanie miniatury za pomocą czerwonej ramki\&.
.IP "\(bu" 2
Emitowanie sygnałów dla interakcji użytkownika (clicked, doubleClicked, hovered, unhovered)\&. 
.PP

.SH "Dokumentacja konstruktora i destruktora"
.PP 
.SS "PhotoItem::PhotoItem (QGraphicsItem * parent = \fCnullptr\fP)\fC [explicit]\fP"

.PP
Konstruktor klasy \fBPhotoItem\fP\&. 
.PP
\fBParametry\fP
.RS 4
\fIparent\fP Opcjonalny wskaźnik na element nadrzędny QGraphicsItem\&.
.RE
.PP
.SH "ConstructorOverview"
.PP
Inicjalizuje obiekt, ustawia domyślne właściwości (brak zaznaczenia, obsługa hover), tworzy ramkę graficzną dla zaznaczenia i konfiguruje jej początkowy stan\&.
.PP
\fBParametry\fP
.RS 4
\fIparent\fP Wskaźnik na opcjonalny element nadrzędny w hierarchii QGraphicsItem\&.
.RE
.PP
.SH "ConstructorOverview"
.PP
Inicjalizuje obiekt jako QObject i QGraphicsPixmapItem, ustawia flagi m_pressed i m_selected na false, tworzy ramkę graficzną (m_frame) jako dziecko, włącza obsługę zdarzeń hover i ustawia początkowy stan ramki (niewidoczna)\&. 
.SS "PhotoItem::~PhotoItem ()"

.PP
Destruktor klasy \fBPhotoItem\fP\&. 
.SH "DestructorOverview"
.PP
Usuwa dynamicznie alokowaną ramkę zaznaczenia (m_frame)\&.
.SH "DestructorOverview"
.PP
Usuwa dynamicznie alokowaną ramkę graficzną (m_frame)\&. 
.SH "Dokumentacja funkcji składowych"
.PP 
.SS "void PhotoItem::clicked (\fBPhotoItem\fP * item)\fC [signal]\fP"

.PP
Sygnał emitowany po jednokrotnym kliknięciu lewym przyciskiem myszy\&. 
.PP
\fBParametry\fP
.RS 4
\fIitem\fP Wskaźnik na kliknięty element \fBPhotoItem\fP\&.
.RE
.PP
.SH "SignalOverview"
.PP
Używany w \fBMainWindow\fP do wyboru miniatury zdjęcia w celu np\&. podglądu lub przygotowania do usunięcia\&. 
.SS "void PhotoItem::doubleClicked (\fBPhotoItem\fP * item)\fC [signal]\fP"

.PP
Sygnał emitowany po dwukrotnym kliknięciu lewym przyciskiem myszy\&. 
.PP
\fBParametry\fP
.RS 4
\fIitem\fP Wskaźnik na kliknięty element \fBPhotoItem\fP\&.
.RE
.PP
.SH "SignalOverview"
.PP
Używany do otwierania zdjęcia w trybie pełnoekranowym z możliwością powiększania i przesuwania\&. 
.SS "void PhotoItem::hovered (\fBPhotoItem\fP * item)\fC [signal]\fP"

.PP
Sygnał emitowany po najechaniu kursorem na obiekt\&. 
.PP
\fBParametry\fP
.RS 4
\fIitem\fP Wskaźnik do obiektu \fBPhotoItem\fP, na który najechano\&.
.RE
.PP
.SH "SignalOverview"
.PP
Może być używany do podświetlania miniatury lub wyświetlania informacji\&. 
.SS "void PhotoItem::hoverEnterEvent (QGraphicsSceneHoverEvent * event)\fC [override]\fP, \fC [protected]\fP"

.PP
Obsługa zdarzenia najechania kursora\&. Obsługuje zdarzenie najechania kursora myszy na obiekt\&.
.PP
\fBParametry\fP
.RS 4
\fIevent\fP Obiekt zawierający dane o zdarzeniu hover enter\&.
.RE
.PP
.SH "MethodOverview"
.PP
Emituje sygnał hovered i przekazuje zdarzenie do QGraphicsPixmapItem\&.
.PP
\fBParametry\fP
.RS 4
\fIevent\fP Zdarzenie typu QGraphicsSceneHoverEvent\&.
.RE
.PP
.SH "MethodOverview"
.PP
Emituje sygnał hovered (np\&. do podświetlenia miniatury) i przekazuje zdarzenie do QGraphicsPixmapItem\&. 
.SS "void PhotoItem::hoverLeaveEvent (QGraphicsSceneHoverEvent * event)\fC [override]\fP, \fC [protected]\fP"

.PP
Obsługa zdarzenia opuszczenia kursora\&. Obsługuje zdarzenie opuszczenia kursora z obiektu\&.
.PP
\fBParametry\fP
.RS 4
\fIevent\fP Obiekt zawierający dane o zdarzeniu hover leave\&.
.RE
.PP
.SH "MethodOverview"
.PP
Emituje sygnał unhovered i przekazuje zdarzenie do QGraphicsPixmapItem\&.
.PP
\fBParametry\fP
.RS 4
\fIevent\fP Zdarzenie typu QGraphicsSceneHoverEvent\&.
.RE
.PP
.SH "MethodOverview"
.PP
Emituje sygnał unhovered (np\&. do usunięcia podświetlenia) i przekazuje zdarzenie do QGraphicsPixmapItem\&. 
.SS "void PhotoItem::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event)\fC [override]\fP, \fC [protected]\fP"

.PP
Obsługa zdarzenia podwójnego kliknięcia myszy\&. Obsługuje podwójne kliknięcie lewym przyciskiem myszy na obiekt\&.
.PP
\fBParametry\fP
.RS 4
\fIevent\fP Obiekt zawierający dane o zdarzeniu podwójnego kliknięcia\&.
.RE
.PP
.SH "MethodOverview"
.PP
Przechwytuje podwójne kliknięcia lewym przyciskiem, emituje sygnał doubleClicked i przekazuje zdarzenie do QGraphicsPixmapItem\&.
.PP
\fBParametry\fP
.RS 4
\fIevent\fP Zdarzenie myszy typu QGraphicsSceneMouseEvent\&.
.RE
.PP
.SH "MethodOverview"
.PP
Emituje sygnał doubleClicked dla lewego przycisku (np\&. do pełnoekranowego podglądu zdjęcia)\&. Inne przyciski są obsługiwane przez QGraphicsPixmapItem\&. 
.SS "void PhotoItem::mousePressEvent (QGraphicsSceneMouseEvent * event)\fC [override]\fP, \fC [protected]\fP"

.PP
Obsługa zdarzenia kliknięcia myszy\&. Obsługuje kliknięcie myszy na obiekt\&.
.PP
\fBParametry\fP
.RS 4
\fIevent\fP Obiekt zawierający dane o zdarzeniu myszy\&.
.RE
.PP
.SH "MethodOverview"
.PP
Przechwytuje kliknięcia (prawy przycisk emituje clicked, lewy przekazywany dla podwójnego kliknięcia) i przekazuje zdarzenie do QGraphicsPixmapItem\&.
.PP
\fBParametry\fP
.RS 4
\fIevent\fP Zdarzenie myszy typu QGraphicsSceneMouseEvent\&.
.RE
.PP
.SH "MethodOverview"
.PP
Emituje sygnał clicked dla prawego przycisku myszy (np\&. do podglądu zdjęcia)\&. Lewy przycisk jest przekazywany do QGraphicsPixmapItem, aby umożliwić wykrycie podwójnego kliknięcia\&. Inne przyciski są obsługiwane domyślnie\&. 
.SS "void PhotoItem::setSelected (bool selected)"

.PP
Ustawia stan zaznaczenia obiektu\&. Ustawia flagę zaznaczenia obiektu i aktualizuje jego ramkę\&.
.PP
\fBParametry\fP
.RS 4
\fIselected\fP Wartość true zaznacza element, false odznacza\&.
.RE
.PP
.SH "MethodOverview"
.PP
Aktualizuje stan zaznaczenia (m_selected) i wywołuje updateFrame() w celu zmiany wyglądu ramki graficznej\&.
.PP
\fBParametry\fP
.RS 4
\fIselected\fP Jeśli true — obiekt będzie wizualnie zaznaczony ramką\&.
.RE
.PP
.SH "MethodOverview"
.PP
Aktualizuje stan m_selected i wywołuje updateFrame, aby wyświetlić lub ukryć czerwoną ramkę wokół miniatury\&. 
.SS "void PhotoItem::unhovered (\fBPhotoItem\fP * item)\fC [signal]\fP"

.PP
Sygnał emitowany po opuszczeniu kursora z obiektu\&. 
.PP
\fBParametry\fP
.RS 4
\fIitem\fP Wskaźnik do obiektu \fBPhotoItem\fP, który przestał być hoverowany\&.
.RE
.PP
.SH "SignalOverview"
.PP
Może być używany do usuwania podświetlenia miniatury\&. 

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Inwentaryzacja\&.
