.TH "src/photoitem.cpp" 3 "So, 3 maj 2025" "Version 1.1.2" "Inwentaryzacja" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/photoitem.cpp \- Implementacja klasy \fBPhotoItem\fP, interaktywnego elementu graficznego dla zdjęć\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'photoitem\&.h'\fP
.br
\fC#include <QGraphicsSceneMouseEvent>\fP
.br
\fC#include <QPainter>\fP
.br
\fC#include <QPen>\fP
.br
\fC#include <QUuid>\fP
.br

.SH "Opis szczegółowy"
.PP 
Implementacja klasy \fBPhotoItem\fP, interaktywnego elementu graficznego dla zdjęć\&. 


.PP
\fBAutor\fP
.RS 4
Stowarzyszenie Miłośników Oldschoolowych Komputerów SMOK & ChatGPT & GROK 
.RE
.PP
\fBWersja\fP
.RS 4
1\&.2\&.2 
.RE
.PP
\fBData\fP
.RS 4
2025-05-03
.RE
.PP
.SH "Overview"
.PP
Plik zawiera implementację metod klasy \fBPhotoItem\fP, która reprezentuje miniaturę zdjęcia w scenie graficznej Qt (QGraphicsView)\&. Klasa rozszerza QGraphicsPixmapItem o obsługę zdarzeń myszy (kliknięcia, podwójne kliknięcia) i hover (najechanie, opuszczenie), a także wizualne zaznaczanie za pomocą czerwonej ramki\&. Dzięki dziedziczeniu po QObject umożliwia emisję sygnałów (clicked, doubleClicked, hovered, unhovered) do integracji z logiką aplikacji, np\&. \fBMainWindow\fP w aplikacji inwentaryzacyjnej\&.
.SH "Structure"
.PP
Kod jest podzielony na następujące sekcje:
.IP "1." 4
\fBKonstruktor\fP – inicjalizuje obiekt, ramkę i zdarzenia\&.
.IP "2." 4
\fBDestruktor\fP – zwalnia zasoby ramki\&.
.IP "3." 4
\fBMetody publiczne\fP – ustawianie stanu zaznaczenia\&.
.IP "4." 4
\fBMetody chronione\fP – obsługa zdarzeń myszy i hover\&.
.IP "5." 4
\fBMetody prywatne\fP – aktualizacja ramki zaznaczenia\&.
.PP
.SH "Dependencies"
.PP
.IP "\(bu" 2
\fBQt Framework\fP: Używa klas QGraphicsSceneMouseEvent, QPainter, QPen, QUuid\&.
.IP "\(bu" 2
\fBNagłówki aplikacji\fP: \fBphotoitem\&.h\fP\&.
.PP
.SH "Notes"
.PP
.IP "\(bu" 2
Kod nie został zmodyfikowany, zgodnie z wymaganiami użytkownika\&. Dodano jedynie komentarze i dokumentację\&.
.IP "\(bu" 2
Klasa jest używana w \fBMainWindow\fP do wyświetlania i interakcji z miniaturami zdjęć eksponatów\&.
.IP "\(bu" 2
Flaga m_pressed jest obecnie nieużywana, ale zachowana dla potencjalnych rozszerzeń\&. 
.PP

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Inwentaryzacja\&.
