.TH "QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN9PhotoItemE_t" 3 "So, 3 maj 2025" "Version 1.1.2" "Inwentaryzacja" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QT_WARNING_DISABLE_DEPRECATED::qt_meta_tag_ZN9PhotoItemE_t
.SH SYNOPSIS
.br
.PP


.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Inwentaryzacja\&.
