.TH "include/types.h" 3 "So, 3 maj 2025" "Version 1.1.2" "Inwentaryzacja" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/types.h \- Deklaracja klasy types służącej do zarządzania typami eksponatów w aplikacji inwentaryzacyjnej\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include <QSqlDatabase>\fP
.br

.SS "Komponenty"

.in +1c
.ti -1c
.RI "class \fBtypes\fP"
.br
.RI "Okno dialogowe do zarządzania typami eksponatów\&. "
.in -1c
.SH "Opis szczegółowy"
.PP 
Deklaracja klasy types służącej do zarządzania typami eksponatów w aplikacji inwentaryzacyjnej\&. 


.PP
\fBWersja\fP
.RS 4
1\&.2\&.2 
.RE
.PP
\fBData\fP
.RS 4
2025-05-03 
.RE
.PP
\fBAutor\fP
.RS 4
Stowarzyszenie Miłośników Oldschoolowych Komputerów SMOK & ChatGPT & GROK
.RE
.PP
.SH "Overview"
.PP
Plik zawiera deklarację klasy types, która reprezentuje okno dialogowe do zarządzania typami eksponatów (np\&. Komputer, Monitor, Drukarka) w aplikacji inwentaryzacyjnej\&. Klasa umożliwia dodawanie, edytowanie i usuwanie typów w tabeli \fCtypes\fP w bazie danych, a także synchronizację z głównym oknem aplikacji (\fC\fBMainWindow\fP\fP) w celu odświeżenia combo boxów po zapisaniu zmian\&.
.SH "Structure"
.PP
Plik nagłówkowy zawiera:
.IP "1." 4
\fBDeklarację klasy types\fP – dziedziczy po QDialog\&.
.IP "2." 4
\fBMetody publiczne\fP – konstruktor, destruktor, ustawianie \fBMainWindow\fP\&.
.IP "3." 4
\fBSloty prywatne\fP – obsługują akcje użytkownika (dodawanie, edycja, usuwanie, zatwierdzanie)\&.
.IP "4." 4
\fBMetody prywatne\fP – odświeżanie listy typów\&.
.IP "5." 4
\fBZmienne prywatne\fP – przechowują interfejs, \fBMainWindow\fP i połączenie z bazą danych\&.
.PP
.SH "Dependencies"
.PP
.IP "\(bu" 2
\fBQt Framework\fP: Używa klas QDialog, QSqlDatabase\&.
.IP "\(bu" 2
\fBNagłówki aplikacji\fP: \fBmainwindow\&.h\fP (deklaracja \fBMainWindow\fP)\&.
.IP "\(bu" 2
\fBNamespace Ui\fP: Zawiera definicję interfejsu użytkownika (\fBui_types\&.h\fP)\&.
.PP
.SH "Notes"
.PP
.IP "\(bu" 2
Kod nie został zmodyfikowany, zgodnie z wymaganiami użytkownika\&. Dodano jedynie komentarze i dokumentację\&.
.IP "\(bu" 2
Klasa jest częścią systemu słownikowego, współpracuje z \fBMainWindow\fP do aktualizacji combo boxów\&.
.IP "\(bu" 2
Obsługuje MySQL, ale aplikacja wspiera także SQLite (konfigurowane w \fBDatabaseConfigDialog\fP)\&. 
.PP

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Inwentaryzacja\&.
