.TH "Ui::itemList" 3 "So, 3 maj 2025" "Version 1.1.2" "Inwentaryzacja" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::itemList
.SH SYNOPSIS
.br
.PP
.PP
Dziedziczy \fBUi_itemList\fP\&.
.SS "Dodatkowe Dziedziczone Składowe"


.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Inwentaryzacja\&.
