.TH "include/utils.h" 3 "So, 3 maj 2025" "Version 1.1.2" "Inwentaryzacja" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/utils.h \- Deklaracja funkcji pomocniczych wykorzystywanych w aplikacji inwentaryzacyjnej\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <QString>\fP
.br

.SS "Funkcje"

.in +1c
.ti -1c
.RI "bool \fBsetupDatabase\fP (const QString &dbType, const QString &dbSource, const QString &host=QString(), const QString &user=QString(), const QString &password=QString(), int port=0)"
.br
.RI "Inicjalizuje połączenie z bazą danych na podstawie podanych parametrów\&. "
.in -1c
.SH "Opis szczegółowy"
.PP 
Deklaracja funkcji pomocniczych wykorzystywanych w aplikacji inwentaryzacyjnej\&. 


.PP
\fBWersja\fP
.RS 4
1\&.2\&.2 
.RE
.PP
\fBData\fP
.RS 4
2025-05-03 
.RE
.PP
\fBAutor\fP
.RS 4
Stowarzyszenie Miłośników Oldschoolowych Komputerów SMOK & ChatGPT & GROK
.RE
.PP
.SH "Overview"
.PP
Plik zawiera deklarację funkcji \fCsetupDatabase\fP, odpowiedzialnej za inicjalizację połączenia z bazą danych (SQLite lub MySQL) z wykorzystaniem parametrów takich jak typ bazy, źródło danych, host, port i dane uwierzytelniające\&. Funkcja jest kluczowym elementem konfiguracji bazy danych w aplikacji inwentaryzacyjnej, ustanawiając globalne połączenie o nazwie 'default_connection', używane przez inne komponenty aplikacji\&.
.SH "Structure"
.PP
Plik nagłówkowy zawiera:
.IP "1." 4
\fBDeklarację funkcji \fCsetupDatabase\fP\fP – konfiguruje i otwiera połączenie z bazą danych\&.
.IP "2." 4
\fBZależności\fP – minimalne, obejmuje tylko \fCQString\fP z Qt\&.
.PP
.SH "Dependencies"
.PP
.IP "\(bu" 2
\fBQt Framework\fP: Używa klasy \fCQString\fP dla parametrów funkcji\&.
.IP "\(bu" 2
\fBNagłówki Qt\fP: Pośrednio zależne od \fCQSqlDatabase\fP (w \fC\fButils\&.cpp\fP\fP)\&.
.PP
.SH "Notes"
.PP
.IP "\(bu" 2
Kod nie został zmodyfikowany, zgodnie z wymaganiami użytkownika\&. Dodano jedynie komentarze i dokumentację\&.
.IP "\(bu" 2
Funkcja \fCsetupDatabase\fP jest wykorzystywana na etapie uruchamiania aplikacji, np\&. w \fC\fBDatabaseConfigDialog\fP\fP\&.
.IP "\(bu" 2
Obsługuje zarówno SQLite (lokalny plik bazy), jak i MySQL (zdalne połączenie)\&. 
.PP

.SH "Dokumentacja funkcji"
.PP 
.SS "bool setupDatabase (const QString & dbType, const QString & dbSource, const QString & host, const QString & user, const QString & password, int port)"

.PP
Inicjalizuje połączenie z bazą danych na podstawie podanych parametrów\&. 
.SH "FunctionOverview"
.PP
Funkcja tworzy i rejestruje globalne połączenie \fCQSqlDatabase\fP pod nazwą 'default_connection'\&. Obsługuje różne typy baz danych (SQLite poprzez \fCQSQLITE\fP, MySQL poprzez \fCQMYSQL\fP) i umożliwia konfigurację połączenia lokalnego (plik SQLite) lub zdalnego (MySQL z hostem, portem, użytkownikiem)\&. W przypadku SQLite automatycznie tworzy schemat bazy danych i wypełnia przykładowymi danymi\&.
.PP
\fBParametry\fP
.RS 4
\fIdbType\fP Typ bazy danych ('SQLite3' lub 'MySQL')\&. 
.br
\fIdbSource\fP Ścieżka do pliku bazy (SQLite) lub nazwa bazy danych (MySQL)\&. 
.br
\fIhost\fP Adres hosta dla połączeń MySQL (np\&. 'localhost', opcjonalny)\&. 
.br
\fIuser\fP Nazwa użytkownika dla MySQL (opcjonalny)\&. 
.br
\fIpassword\fP Hasło użytkownika dla MySQL (opcjonalny)\&. 
.br
\fIport\fP Numer portu dla MySQL (domyślnie 3306, opcjonalny)\&. 
.RE
.PP
\fBZwraca\fP
.RS 4
true jeśli połączenie zostało pomyślnie nawiązane, false w przypadku błędu\&.
.RE
.PP
Inicjalizuje połączenie z bazą danych na podstawie podanych parametrów\&.
.SH "FunctionOverview"
.PP
Funkcja konfiguruje połączenie z bazą danych SQLite (\fCQSQLITE\fP) lub MySQL (\fCQMYSQL\fP)\&. Dla SQLite \fCdbSource\fP to ścieżka do pliku bazy, dla MySQL to nazwa bazy danych\&. Jeśli połączenie 'default_connection' istnieje, jest usuwane i tworzone od nowa\&. Dla SQLite automatycznie tworzy schemat bazy (tabele i dane początkowe) jeśli nie istnieje\&.
.PP
\fBParametry\fP
.RS 4
\fIdbType\fP Typ bazy danych ('SQLite3' lub 'MySQL')\&. 
.br
\fIdbSource\fP Dla SQLite – ścieżka do pliku; dla MySQL – nazwa bazy danych\&. 
.br
\fIhost\fP Adres hosta dla MySQL (np\&. 'localhost', opcjonalny)\&. 
.br
\fIuser\fP Nazwa użytkownika dla MySQL (opcjonalny)\&. 
.br
\fIpassword\fP Hasło użytkownika dla MySQL (opcjonalny)\&. 
.br
\fIport\fP Numer portu dla MySQL (domyślnie 3306, opcjonalny)\&. 
.RE
.PP
\fBZwraca\fP
.RS 4
\fCtrue\fP jeśli połączenie zostało nawiązane pomyślnie; \fCfalse\fP w przypadku błędu\&. 
.RE
.PP

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Inwentaryzacja\&.
