.TH "src/vendors.cpp" 3 "So, 3 maj 2025" "Version 1.1.2" "Inwentaryzacja" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/vendors.cpp \- Implementacja klasy vendors do zarządzania producentami sprzętu w aplikacji inwentaryzacyjnej\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'vendors\&.h'\fP
.br
\fC#include <QInputDialog>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QSqlError>\fP
.br
\fC#include <QSqlQuery>\fP
.br
\fC#include <QSqlQueryModel>\fP
.br
\fC#include <QUuid>\fP
.br
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'ui_vendors\&.h'\fP
.br

.SH "Opis szczegółowy"
.PP 
Implementacja klasy vendors do zarządzania producentami sprzętu w aplikacji inwentaryzacyjnej\&. 


.PP
\fBWersja\fP
.RS 4
1\&.2\&.2 
.RE
.PP
\fBData\fP
.RS 4
2025-05-03 
.RE
.PP
\fBAutor\fP
.RS 4
Stowarzyszenie Miłośników Oldschoolowych Komputerów SMOK & ChatGPT & GROK
.RE
.PP
.SH "Overview"
.PP
Plik zawiera implementację metod klasy vendors, odpowiedzialnej za zarządzanie producentami sprzętu (np\&. Commodore, IBM, Apple) w bazie danych (tabela \fCvendors\fP)\&. Klasa umożliwia dodawanie, edytowanie i usuwanie producentów, współpracując z interfejsem użytkownika (QListView, QLineEdit) oraz klasą \fBMainWindow\fP w celu odświeżania combo boxów po zapisaniu zmian\&.
.SH "Structure"
.PP
Kod jest podzielony na następujące sekcje:
.IP "1." 4
\fBKonstruktor\fP – inicjalizuje interfejs, połączenie z bazą danych, sloty\&.
.IP "2." 4
\fBDestruktor\fP – zwalnia zasoby\&.
.IP "3." 4
\fBMetody publiczne\fP – ustawianie \fBMainWindow\fP\&.
.IP "4." 4
\fBSloty prywatne\fP – obsługują akcje użytkownika (dodawanie, edycja, usuwanie, zatwierdzanie)\&.
.IP "5." 4
\fBMetody prywatne\fP – odświeżanie listy producentów\&.
.PP
.SH "Dependencies"
.PP
.IP "\(bu" 2
\fBQt Framework\fP: Używa klas QMessageBox, QSqlQuery, QSqlQueryModel, QInputDialog, QUuid\&.
.IP "\(bu" 2
\fBNagłówki aplikacji\fP: \fBvendors\&.h\fP, \fBmainwindow\&.h\fP\&.
.IP "\(bu" 2
\fBInterfejs użytkownika\fP: \fBui_vendors\&.h\fP\&.
.PP
.SH "Notes"
.PP
.IP "\(bu" 2
Kod nie został zmodyfikowany, zgodnie z wymaganiami użytkownika\&. Dodano jedynie komentarze i dokumentację\&.
.IP "\(bu" 2
Klasa jest częścią systemu słownikowego, integruje się z \fBMainWindow\fP\&.
.IP "\(bu" 2
Obsługuje MySQL, ale aplikacja wspiera także SQLite (konfigurowane w \fBDatabaseConfigDialog\fP)\&. 
.PP

.SH "Autor"
.PP 
Wygenerowano automatycznie z kodu źródłowego programem Doxygen dla Inwentaryzacja\&.
