PhotoItem
bool PhotoItem::m_pressed
Flaga oznaczająca, czy obiekt został kliknięty.
VariableOverview Obecnie nieużywana w implementacji, zachowana dla potencjalnych rozszerzeń.
bool PhotoItem::m_selected
Flaga oznaczająca, czy obiekt jest zaznaczony.
VariableOverview Kontroluje, czy ramka zaznaczenia (m_frame) jest wyświetlana.
QGraphicsRectItem* PhotoItem::m_frame
Ramka graficzna wykorzystywana do oznaczania zaznaczenia.
VariableOverview Obiekt QGraphicsRectItem wyświetlający czerwoną ramkę wokół miniatury przy zaznaczeniu (m_selected == true).
PhotoItem::PhotoItem(QGraphicsItem *parent=nullptr)
Konstruktor klasy PhotoItem.
parent Opcjonalny wskaźnik na element nadrzędny QGraphicsItem. ConstructorOverview Inicjalizuje obiekt, ustawia domyślne właściwości (brak zaznaczenia, obsługa hover), tworzy ramkę graficzną dla zaznaczenia i konfiguruje jej początkowy stan. parent Wskaźnik na opcjonalny element nadrzędny w hierarchii QGraphicsItem. ConstructorOverview Inicjalizuje obiekt jako QObject i QGraphicsPixmapItem, ustawia flagi m_pressed i m_selected na false, tworzy ramkę graficzną (m_frame) jako dziecko, włącza obsługę zdarzeń hover i ustawia początkowy stan ramki (niewidoczna).
PhotoItem::~PhotoItem()
Destruktor klasy PhotoItem.
DestructorOverview Usuwa dynamicznie alokowaną ramkę zaznaczenia (m_frame). DestructorOverview Usuwa dynamicznie alokowaną ramkę graficzną (m_frame).
void PhotoItem::setSelected(bool selected)
Ustawia stan zaznaczenia obiektu.
Ustawia flagę zaznaczenia obiektu i aktualizuje jego ramkę. selected Wartość true zaznacza element, false odznacza. MethodOverview Aktualizuje stan zaznaczenia (m_selected) i wywołuje updateFrame() w celu zmiany wyglądu ramki graficznej. selected Jeśli true — obiekt będzie wizualnie zaznaczony ramką. MethodOverview Aktualizuje stan m_selected i wywołuje updateFrame, aby wyświetlić lub ukryć czerwoną ramkę wokół miniatury.
void PhotoItem::clicked(PhotoItem *item)
Sygnał emitowany po jednokrotnym kliknięciu lewym przyciskiem myszy.
item Wskaźnik na kliknięty element PhotoItem. SignalOverview Używany w MainWindow do wyboru miniatury zdjęcia w celu np. podglądu lub przygotowania do usunięcia.
Referenced by mousePressEvent.
void PhotoItem::doubleClicked(PhotoItem *item)
Sygnał emitowany po dwukrotnym kliknięciu lewym przyciskiem myszy.
item Wskaźnik na kliknięty element PhotoItem. SignalOverview Używany do otwierania zdjęcia w trybie pełnoekranowym z możliwością powiększania i przesuwania.
Referenced by mouseDoubleClickEvent.
void PhotoItem::hovered(PhotoItem *item)
Sygnał emitowany po najechaniu kursorem na obiekt.
item Wskaźnik do obiektu PhotoItem, na który najechano. SignalOverview Może być używany do podświetlania miniatury lub wyświetlania informacji.
Referenced by hoverEnterEvent.
void PhotoItem::unhovered(PhotoItem *item)
Sygnał emitowany po opuszczeniu kursora z obiektu.
item Wskaźnik do obiektu PhotoItem, który przestał być hoverowany. SignalOverview Może być używany do usuwania podświetlenia miniatury.
Referenced by hoverLeaveEvent.
void PhotoItem::mousePressEvent(QGraphicsSceneMouseEvent *event) override
Obsługa zdarzenia kliknięcia myszy.
Obsługuje kliknięcie myszy na obiekt. event Obiekt zawierający dane o zdarzeniu myszy. MethodOverview Przechwytuje kliknięcia (prawy przycisk emituje clicked, lewy przekazywany dla podwójnego kliknięcia) i przekazuje zdarzenie do QGraphicsPixmapItem. event Zdarzenie myszy typu QGraphicsSceneMouseEvent. MethodOverview Emituje sygnał clicked dla prawego przycisku myszy (np. do podglądu zdjęcia). Lewy przycisk jest przekazywany do QGraphicsPixmapItem, aby umożliwić wykrycie podwójnego kliknięcia. Inne przyciski są obsługiwane domyślnie.
References clicked.
void PhotoItem::mouseDoubleClickEvent(QGraphicsSceneMouseEvent *event) override
Obsługa zdarzenia podwójnego kliknięcia myszy.
Obsługuje podwójne kliknięcie lewym przyciskiem myszy na obiekt. event Obiekt zawierający dane o zdarzeniu podwójnego kliknięcia. MethodOverview Przechwytuje podwójne kliknięcia lewym przyciskiem, emituje sygnał doubleClicked i przekazuje zdarzenie do QGraphicsPixmapItem. event Zdarzenie myszy typu QGraphicsSceneMouseEvent. MethodOverview Emituje sygnał doubleClicked dla lewego przycisku (np. do pełnoekranowego podglądu zdjęcia). Inne przyciski są obsługiwane przez QGraphicsPixmapItem.
References doubleClicked.
void PhotoItem::hoverEnterEvent(QGraphicsSceneHoverEvent *event) override
Obsługa zdarzenia najechania kursora.
Obsługuje zdarzenie najechania kursora myszy na obiekt. event Obiekt zawierający dane o zdarzeniu hover enter. MethodOverview Emituje sygnał hovered i przekazuje zdarzenie do QGraphicsPixmapItem. event Zdarzenie typu QGraphicsSceneHoverEvent. MethodOverview Emituje sygnał hovered (np. do podświetlenia miniatury) i przekazuje zdarzenie do QGraphicsPixmapItem.
References hovered.
void PhotoItem::hoverLeaveEvent(QGraphicsSceneHoverEvent *event) override
Obsługa zdarzenia opuszczenia kursora.
Obsługuje zdarzenie opuszczenia kursora z obiektu. event Obiekt zawierający dane o zdarzeniu hover leave. MethodOverview Emituje sygnał unhovered i przekazuje zdarzenie do QGraphicsPixmapItem. event Zdarzenie typu QGraphicsSceneHoverEvent. MethodOverview Emituje sygnał unhovered (np. do usunięcia podświetlenia) i przekazuje zdarzenie do QGraphicsPixmapItem.
References unhovered.
void PhotoItem::updateFrame()
Aktualizuje wygląd ramki zaznaczenia w zależności od stanu.
Aktualizuje wygląd ramki zaznaczenia w zależności od stanu zaznaczenia. MethodOverview Ustawia czerwoną ramkę o szerokości 2 piksele, gdy obiekt jest zaznaczony, lub ukrywa ramkę, gdy nie jest zaznaczony. MethodOverview Jeśli m_selected jest true, ustawia czerwoną ramkę o szerokości 2 piksele wokół miniatury (z marginesem -2, +2 piksele). W przeciwnym razie ukrywa ramkę poprzez ustawienie Qt::NoPen.