DatabaseConfigDialog
Ui::DatabaseConfigDialog* DatabaseConfigDialog::ui
Wskaźnik na obiekt interfejsu użytkownika.
int DatabaseConfigDialog::m_topazFontId
ID czcionki Topaz załadowanej z zasobów.
int DatabaseConfigDialog::m_zxFontId
ID czcionki ZX Spectrum załadowanej z zasobów.
int DatabaseConfigDialog::m_atari8bitFontId
ID czcionki Atari 8bit załadowanej z zasobów.
DatabaseConfigDialog::DatabaseConfigDialog(QWidget *parent=nullptr)
Konstruktor klasy DatabaseConfigDialog.
parent Wskaźnik na nadrzędny widget. Domyślnie nullptr. ConstructorOverview Inicjalizuje okno dialogowe, konfiguruje interfejs użytkownika (ui), ładuje dostępne skórki graficzne, ustawia opcje combo boxów i wczytuje zapisane ustawienia z QSettings. Ustawia połączenia sygnałów i slotów dla dynamicznej interakcji z użytkownikiem. parent Wskaźnik na nadrzędny widget. Domyślnie nullptr. ConstructorOverview Inicjalizuje interfejs użytkownika, ustawia opcje combo boxów dla typu bazy danych (SQLite3, MySQL) i skórek graficznych (Amiga, Atari 8bit, ZX Spectrum, Standard). Ładuje zapisane ustawienia z QSettings, konfiguruje początkowy stan interfejsu i ustanawia połączenia sygnałów-slotów dla interakcji użytkownika, w tym wybór pliku SQLite.
References accept.
DatabaseConfigDialog::~DatabaseConfigDialog()
Destruktor klasy DatabaseConfigDialog.
DestructorOverview Zwalnia zasoby interfejsu użytkownika (ui) oraz usuwa załadowane czcionki z QFontDatabase, aby zapobiec wyciekom pamięci. DestructorOverview Zwalnia zasoby interfejsu użytkownika (ui) oraz usuwa załadowane czcionki (Topaz, ZX Spectrum, Atari 8bit) z QFontDatabase, aby zapobiec wyciekom pamięci.
QString DatabaseConfigDialog::selectedDatabaseType() const
Zwraca wybrany typ bazy danych.
QString zawierający typ bazy danych (np. "SQLite3" lub "MySQL"). MethodOverview Pobiera aktualnie wybrany typ bazy danych z combo boxa dbTypeComboBox. QString zawierający typ bazy danych. MethodOverview Pobiera tekst wybrany w combo boxie dbTypeComboBox, reprezentujący typ bazy danych (SQLite3 lub MySQL).
Referenced by main.
QString DatabaseConfigDialog::sqliteFilePath() const
Zwraca ścieżkę do pliku bazy SQLite.
QString zawierający ścieżkę do pliku SQLite. MethodOverview Zwraca ścieżkę do pliku bazy SQLite wprowadzoną w polu sqlitePathLineEdit. QString zawierający ścieżkę do pliku SQLite. MethodOverview Zwraca tekst z pola sqlitePathLineEdit, zawierający ścieżkę do pliku bazy SQLite.
Referenced by main.
QString DatabaseConfigDialog::mysqlHost() const
Zwraca adres hosta dla bazy MySQL.
QString zawierający adres hosta MySQL. MethodOverview Zwraca adres hosta MySQL wprowadzony w polu hostLineEdit. QString zawierający adres hosta MySQL. MethodOverview Zwraca tekst z pola hostLineEdit, zawierający adres hosta bazy MySQL.
Referenced by main.
QString DatabaseConfigDialog::mysqlDatabase() const
Zwraca nazwę bazy danych MySQL.
QString zawierający nazwę bazy danych MySQL. MethodOverview Zwraca nazwę bazy danych MySQL wprowadzoną w polu databaseLineEdit. QString zawierający nazwę bazy danych MySQL. MethodOverview Zwraca tekst z pola databaseLineEdit, zawierający nazwę bazy danych MySQL.
Referenced by main.
QString DatabaseConfigDialog::mysqlUser() const
Zwraca nazwę użytkownika dla bazy MySQL.
QString zawierający nazwę użytkownika MySQL. MethodOverview Zwraca nazwę użytkownika MySQL wprowadzoną w polu userLineEdit. QString zawierający nazwę użytkownika MySQL. MethodOverview Zwraca tekst z pola userLineEdit, zawierający nazwę użytkownika bazy MySQL.
Referenced by main.
QString DatabaseConfigDialog::mysqlPassword() const
Zwraca hasło użytkownika dla bazy MySQL.
QString zawierający hasło użytkownika MySQL. MethodOverview Zwraca hasło użytkownika MySQL wprowadzone w polu passwordLineEdit. QString zawierający hasło użytkownika MySQL. MethodOverview Zwraca tekst z pola passwordLineEdit, zawierający hasło użytkownika bazy MySQL.
Referenced by main.
int DatabaseConfigDialog::mysqlPort() const
Zwraca numer portu dla bazy MySQL.
int zawierający numer portu MySQL. MethodOverview Zwraca numer portu MySQL wprowadzony w polu portSpinBox. int zawierający numer portu MySQL. MethodOverview Zwraca wartość z pola portSpinBox, reprezentującą numer portu bazy MySQL.
Referenced by main.
void DatabaseConfigDialog::accept() override
Zatwierdza wprowadzone dane i zamyka okno dialogowe.
SlotOverview Przesłania metodę accept() klasy QDialog. Zapisuje wszystkie wprowadzone parametry (typ bazy danych, ścieżka SQLite, dane MySQL, wybrana skórka) w QSettings i zamyka okno dialogowe z wynikiem QDialog::Accepted. MethodOverview Zapisuje wszystkie wprowadzone parametry (typ bazy danych, ścieżka SQLite, dane MySQL, wybrana skórka) w pliku inwentaryzacja.ini za pomocą QSettings, a następnie wywołuje metodę accept klasy QDialog, zamykając okno z wynikiem QDialog::Accepted.
Referenced by DatabaseConfigDialog.
void DatabaseConfigDialog::onDatabaseTypeChanged(int index)
Obsługuje zmianę typu bazy danych w combo boxie.
index Indeks wybranego typu bazy danych. SlotOverview Aktualizuje widoczność pól w interfejsie użytkownika (QStackedWidget) w zależności od wybranego typu bazy danych (SQLite lub MySQL). index Indeks wybranego typu bazy danych. SlotOverview Przełącza aktywną stronę w QStackedWidget, pokazując odpowiednie pola dla wybranego typu bazy danych (SQLite lub MySQL).
void DatabaseConfigDialog::onSkinChanged(const QString &skin)
Obsługuje zmianę skórki graficznej.
skin Nazwa wybranej skórki (np. "Amiga", "ZX Spectrum", "Standard"). SlotOverview Wywołuje metody loadStyleSheet i loadFont dla wybranej skórki, aktualizuje interfejs aplikacji i zapisuje wybór w QSettings. skin Nazwa wybranej skórki (np. "Amiga", "ZX Spectrum", "Standard"). SlotOverview Wywołuje metody loadStyleSheet i loadFont dla wybranej skórki, aktualizuje styl i czcionkę aplikacji, zapisuje wybór w QSettings i loguje zmianę.
void DatabaseConfigDialog::loadStyleSheet(const QString &skin)
Ładuje arkusz stylów dla wybranej skórki.
skin Nazwa skórki (np. "Amiga", "ZX Spectrum", "Standard"). MethodOverview Wczytuje odpowiedni plik QSS z zasobów Qt (np. :/styles/amiga.qss) i stosuje go do aplikacji za pomocą qApp->setStyleSheet. W przypadku błędu loguje ostrzeżenie. skin Nazwa skórki (np. "Amiga", "ZX Spectrum", "Standard"). MethodOverview Mapuje nazwę skórki na odpowiedni plik QSS w zasobach Qt (np. :/styles/amiga.qss), wczytuje jego zawartość i stosuje do aplikacji za pomocą qApp->setStyleSheet. Loguje sukces lub błąd ładowania.
void DatabaseConfigDialog::loadFont(const QString &skin)
Ładuje czcionkę dla wybranej skórki.
skin Nazwa skórki (np. "Amiga", "ZX Spectrum", "Standard"). MethodOverview Ładuje odpowiednią czcionkę z zasobów Qt (np. topaz.ttf dla Amigi) za pomocą QFontDatabase i ustawia ją dla aplikacji za pomocą qApp->setFont. W przypadku Standard używa domyślnej czcionki systemowej. skin Nazwa skórki (np. "Amiga", "ZX Spectrum", "Standard"). MethodOverview Mapuje nazwę skórki na odpowiednią czcionkę (np. topaz.ttf dla Amigi, zxspectrum.ttf dla ZX Spectrum, EightBit Atari-Ataripl.ttf dla Atari 8bit, domyślna systemowa dla Standard). Ładuje czcionkę za pomocą QFontDatabase, ustawia ją dla aplikacji za pomocą qApp->setFont i aktualizuje paletę oraz styl, aby zapewnić propagację czcionki. Loguje sukces lub błąd ładowania.